### ISSUE TITLE
Could not pass event BlockIgniteEvent to ASkyBlock v3.0.6.1

### ISSUE THREAD

**Issue by L4BORG** [tastybento/ASkyBlock-Bugs-N-Features#103]
```
[03:57:56 ERROR]: Could not pass event BlockIgniteEvent to ASkyBlock v3.0.6.1
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[patched.jar:git-TacoSpigot-"65fd35f"]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[patched.jar:git-TacoSpigot-"65fd35f"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched.jar:git-TacoSpigot-"65fd35f"]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [patched.jar:git-TacoSpigot-"65fd35f"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [patched.jar:git-TacoSpigot-"65fd35f"]
        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callBlockIgniteEvent(CraftEventFactory.java:807) [patched.jar:git-TacoSpigot-"65fd35f"]
        at net.minecraft.server.v1_8_R3.DispenserRegistry$12.b(DispenserRegistry.java:431) [patched.jar:git-TacoSpigot-"65fd35f"]
        at net.minecraft.server.v1_8_R3.DispenseBehaviorItem.a(DispenseBehaviorItem.java:13) [patched.jar:git-TacoSpigot-"65fd35f"]
        at net.minecraft.server.v1_8_R3.BlockDispenser.dispense(BlockDispenser.java:86) [patched.jar:git-TacoSpigot-"65fd35f"]
        at net.minecraft.server.v1_8_R3.BlockDispenser.b(BlockDispenser.java:115) [patched.jar:git-TacoSpigot-"65fd35f"]
        at net.minecraft.server.v1_8_R3.WorldServer.a(WorldServer.java:684) [patched.jar:git-TacoSpigot-"65fd35f"]
        at net.minecraft.server.v1_8_R3.WorldServer.doTick(WorldServer.java:249) [patched.jar:git-TacoSpigot-"65fd35f"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:830) [patched.jar:git-TacoSpigot-"65fd35f"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [patched.jar:git-TacoSpigot-"65fd35f"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [patched.jar:git-TacoSpigot-"65fd35f"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched.jar:git-TacoSpigot-"65fd35f"]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.NullPointerException
        at com.wasteofplastic.askyblock.listeners.IslandGuard.onBlockIgnite(IslandGuard.java:2432) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor399.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[patched.jar:git-TacoSpigot-"65fd35f"]
        ... 16 more
```

but I'm not sure how to replicate it...

**Comment by Poslovitch** [comment]
It's not really "replicatable".
I'll have a look to this error.

Does it happen often? When? Does it happen when a specific player is online? When a specific island is loaded?

**Comment by tastybento** [comment]
@L4BORG Do you use Citizens?

Line 2432 in IslandGuard is:

```
                if (e.getPlayer().isOp() || VaultHelper.checkPerm(e.getPlayer(), Settings.PERMPREFIX + "mod.bypass")) {
```

So it means that e.getPlayer() is null. So, could a citizen be using Flint & Steel?

**Comment by L4BORG** [comment]
No, but we use lib's disguises to spawn NPCs. None of them use Flint & Steel tho.

**Comment by tastybento** [comment]
From the Java docs it is possible for the getPlayer() to be null if the event was not caused by a player. I'm not sure how a flint and steel action to ignite a block can happen without a player, but it did, so I've added null checks to avoid it in the future.

**Comment by tastybento** [comment]
Fixed by a906c673e0d54df2c981e677a17be73dc33e4b46

**Comment by Poslovitch** [comment]
It can happen with a ddispenser

**Comment by tastybento** [comment]
YES! Well done! That's how it happens. Now I can test it.
