### ISSUE TITLE
Сhallenges and Potions: IllegalArgumentException

### ISSUE THREAD

**Issue by IO-div** [tastybento/ASkyBlock-Bugs-N-Features#134]
Server & ASkyBlock version: Bukkit 1.7.10 / v3.0.6.3
Error log:
```
[Server thread/ERROR]: Could not pass event InventoryClickEvent to ASkyBlock v3.0.6.3
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:509) [spigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:494) [spigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:1477) [spigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at net.minecraft.server.v1_7_R4.PacketPlayInWindowClick.a(PacketPlayInWindowClick.java:15) [spigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at net.minecraft.server.v1_7_R4.PacketPlayInWindowClick.handle(PacketPlayInWindowClick.java:65) [spigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:186) [spigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81) [spigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:734) [spigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) [spigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) [spigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [spigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [spigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
Caused by: org.bukkit.command.CommandException: Unhandled exception executing command 'asc' in plugin ASkyBlock v3.0.6.3
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) ~[spigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:767) ~[spigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at org.bukkit.craftbukkit.v1_7_R4.entity.CraftPlayer.performCommand(CraftPlayer.java:282) ~[spigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at com.wasteofplastic.askyblock.panels.ControlPanel.onInventoryClick(ControlPanel.java:288) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor161.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_101]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_101]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:298) ~[spigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	... 13 more
Caused by: java.lang.IllegalArgumentException: Instant potions cannot be extended
	at org.apache.commons.lang.Validate.isTrue(Validate.java:136) ~[spigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at org.bukkit.potion.Potion.setHasExtendedDuration(Potion.java:262) ~[spigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at org.bukkit.potion.Potion.extend(Potion.java:146) ~[spigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at org.bukkit.potion.Potion.fromDamage(Potion.java:401) ~[spigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at org.bukkit.potion.Potion.fromItemStack(Potion.java:410) ~[spigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at com.wasteofplastic.askyblock.commands.Challenges.hasRequired(Challenges.java:1196) ~[?:?]
	at com.wasteofplastic.askyblock.commands.Challenges.checkIfCanCompleteChallenge(Challenges.java:834) ~[?:?]
	at com.wasteofplastic.askyblock.commands.Challenges.onCommand(Challenges.java:204) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) ~[spigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:767) ~[spigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at org.bukkit.craftbukkit.v1_7_R4.entity.CraftPlayer.performCommand(CraftPlayer.java:282) ~[spigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at com.wasteofplastic.askyblock.panels.ControlPanel.onInventoryClick(ControlPanel.java:288) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor161.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_101]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_101]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:298) ~[spigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	... 13 more
```

**Comment by tastybento** [comment]
The potion required in challenges is not possible to be an extended potion. Is this with the stock challenges.yml or did you make your own challenge?

**Comment by SyborgLOL** [comment]
i have same error with stock configs on spigot 1.8

**Comment by SyborgLOL** [comment]
Any progress in this issue??? This prevents progress to new levels

**Comment by tastybento** [comment]
What is happening here is that the plugin is going through the player's inventory and checking what the potion type is, etc. It turns out that one of the potions in your inventory is an extended potion that according to Bukkit should not exist. Do you have any custom potions? What potions do you have in your inventory and where did they come from?

**Comment by tastybento** [comment]
I've added code that should ignore potions items that Bukkit do not think exist.
