### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by bertek41** [tastybento/ASkyBlock-Bugs-N-Features#163]
`[22:59:55 ERROR]: Could not pass event EntityChangeBlockEvent to ASkyBlock v3.0.6.3
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[craftbukkit.jar:git-PaperSpigot-"8b18730"]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[craftbukkit.jar:git-PaperSpigot-"8b18730"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit.jar:git-PaperSpigot-"8b18730"]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [craftbukkit.jar:git-PaperSpigot-"8b18730"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [craftbukkit.jar:git-PaperSpigot-"8b18730"]
        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEntityChangeBlockEvent(CraftEventFactory.java:682) [craftbukkit.jar:git-PaperSpigot-"8b18730"]
        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEntityChangeBlockEvent(CraftEventFactory.java:665) [craftbukkit.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.PathfinderGoalEatTile.e(PathfinderGoalEatTile.java:69) [craftbukkit.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.PathfinderGoalSelector.a(PathfinderGoalSelector.java:91) [craftbukkit.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.EntityInsentient.doTick(EntityInsentient.java:480) [craftbukkit.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.EntityLiving.m(EntityLiving.java:1631) [craftbukkit.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.EntityInsentient.m(EntityInsentient.java:339) [craftbukkit.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.EntityAgeable.m(EntityAgeable.java:139) [craftbukkit.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.EntityAnimal.m(EntityAnimal.java:23) [craftbukkit.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.EntitySheep.m(EntitySheep.java:63) [craftbukkit.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.EntityLiving.t_(EntityLiving.java:1495) [craftbukkit.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.EntityInsentient.t_(EntityInsentient.java:194) [craftbukkit.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.World.entityJoinedWorld(World.java:1644) [craftbukkit.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.World.g(World.java:1611) [craftbukkit.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.World.tickEntities(World.java:1448) [craftbukkit.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.WorldServer.tickEntities(WorldServer.java:600) [craftbukkit.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:846) [craftbukkit.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [craftbukkit.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [craftbukkit.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [craftbukkit.jar:git-PaperSpigot-"8b18730"]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
Caused by: java.lang.NullPointerException
        at com.wasteofplastic.askyblock.listeners.IslandGuard.actionAllowed(IslandGuard.java:219) ~[?:?]
        at com.wasteofplastic.askyblock.listeners.IslandGuard.onTNTPrimed(IslandGuard.java:2629) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_131]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[craftbukkit.jar:git-PaperSpigot-"8b18730"]
        ... 25 more
[23:00:59 ERROR]: Could not pass event EntityChangeBlockEvent to ASkyBlock v3.0.6.3
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[craftbukkit.jar:git-PaperSpigot-"8b18730"]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[craftbukkit.jar:git-PaperSpigot-"8b18730"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit.jar:git-PaperSpigot-"8b18730"]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [craftbukkit.jar:git-PaperSpigot-"8b18730"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [craftbukkit.jar:git-PaperSpigot-"8b18730"]
        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEntityChangeBlockEvent(CraftEventFactory.java:682) [craftbukkit.jar:git-PaperSpigot-"8b18730"]
        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEntityChangeBlockEvent(CraftEventFactory.java:665) [craftbukkit.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.PathfinderGoalEatTile.e(PathfinderGoalEatTile.java:59) [craftbukkit.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.PathfinderGoalSelector.a(PathfinderGoalSelector.java:91) [craftbukkit.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.EntityInsentient.doTick(EntityInsentient.java:480) [craftbukkit.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.EntityLiving.m(EntityLiving.java:1631) [craftbukkit.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.EntityInsentient.m(EntityInsentient.java:339) [craftbukkit.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.EntityAgeable.m(EntityAgeable.java:139) [craftbukkit.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.EntityAnimal.m(EntityAnimal.java:23) [craftbukkit.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.EntitySheep.m(EntitySheep.java:63) [craftbukkit.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.EntityLiving.t_(EntityLiving.java:1495) [craftbukkit.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.EntityInsentient.t_(EntityInsentient.java:194) [craftbukkit.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.World.entityJoinedWorld(World.java:1644) [craftbukkit.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.World.g(World.java:1611) [craftbukkit.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.World.tickEntities(World.java:1448) [craftbukkit.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.WorldServer.tickEntities(WorldServer.java:600) [craftbukkit.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:846) [craftbukkit.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [craftbukkit.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [craftbukkit.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [craftbukkit.jar:git-PaperSpigot-"8b18730"]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
Caused by: java.lang.NullPointerException
        at com.wasteofplastic.askyblock.listeners.IslandGuard.actionAllowed(IslandGuard.java:219) ~[?:?]
        at com.wasteofplastic.askyblock.listeners.IslandGuard.onTNTPrimed(IslandGuard.java:2629) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_131]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[craftbukkit.jar:git-PaperSpigot-"8b18730"]
        ... 25 more
[23:02:38 ERROR]: Could not pass event EntityChangeBlockEvent to ASkyBlock v3.0.6.3
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[craftbukkit.jar:git-PaperSpigot-"8b18730"]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[craftbukkit.jar:git-PaperSpigot-"8b18730"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit.jar:git-PaperSpigot-"8b18730"]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [craftbukkit.jar:git-PaperSpigot-"8b18730"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [craftbukkit.jar:git-PaperSpigot-"8b18730"]
        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEntityChangeBlockEvent(CraftEventFactory.java:682) [craftbukkit.jar:git-PaperSpigot-"8b18730"]
        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEntityChangeBlockEvent(CraftEventFactory.java:665) [craftbukkit.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.PathfinderGoalEatTile.e(PathfinderGoalEatTile.java:69) [craftbukkit.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.PathfinderGoalSelector.a(PathfinderGoalSelector.java:91) [craftbukkit.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.EntityInsentient.doTick(EntityInsentient.java:480) [craftbukkit.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.EntityLiving.m(EntityLiving.java:1631) [craftbukkit.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.EntityInsentient.m(EntityInsentient.java:339) [craftbukkit.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.EntityAgeable.m(EntityAgeable.java:139) [craftbukkit.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.EntityAnimal.m(EntityAnimal.java:23) [craftbukkit.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.EntitySheep.m(EntitySheep.java:63) [craftbukkit.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.EntityLiving.t_(EntityLiving.java:1495) [craftbukkit.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.EntityInsentient.t_(EntityInsentient.java:194) [craftbukkit.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.World.entityJoinedWorld(World.java:1644) [craftbukkit.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.World.g(World.java:1611) [craftbukkit.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.World.tickEntities(World.java:1448) [craftbukkit.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.WorldServer.tickEntities(WorldServer.java:600) [craftbukkit.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:846) [craftbukkit.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [craftbukkit.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [craftbukkit.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [craftbukkit.jar:git-PaperSpigot-"8b18730"]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
Caused by: java.lang.NullPointerException
        at com.wasteofplastic.askyblock.listeners.IslandGuard.actionAllowed(IslandGuard.java:219) ~[?:?]
        at com.wasteofplastic.askyblock.listeners.IslandGuard.onTNTPrimed(IslandGuard.java:2629) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_131]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[craftbukkit.jar:git-PaperSpigot-"8b18730"]
        ... 25 more`
It is spamming
Server Version: [23:06:04 INFO]: This server is running CraftBukkit version git-PaperSpigot-"8b18730" (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

**Comment by tastybento** [comment]
@bertek41 You config.yml file must be missing the world settings. Have a look at this file and see if you have all the protection.world settings.
https://github.com/tastybento/askyblock/blob/master/config.yml#L647

I will make a change in 3.0.6.4 to use defaults if they are missing, but as a workaround, you need to update your config.yml file to include them.
