### ISSUE TITLE
ASkyBlock v3.0.6.4 generated an exception while executing task ...

### ISSUE THREAD

**Issue by L4BORG** [tastybento/ASkyBlock-Bugs-N-Features#178]
```[17:41:43 WARN]: Exception in thread "Craft Scheduler Thread - 173"
[17:41:43 WARN]: org.apache.commons.lang.UnhandledException: Plugin ASkyBlock v3.0.6.4 generated an exception while executing task 199379
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 16
        at org.bukkit.craftbukkit.v1_8_R3.CraftChunkSnapshot.getBlockTypeId(CraftChunkSnapshot.java:56)
        at com.wasteofplastic.askyblock.SafeSpotTeleport$1.checkBlock(SafeSpotTeleport.java:267)
        at com.wasteofplastic.askyblock.SafeSpotTeleport$1.run(SafeSpotTeleport.java:158)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more
[17:41:51 WARN]: Exception in thread "Craft Scheduler Thread - 174"
[17:41:51 WARN]: org.apache.commons.lang.UnhandledException: Plugin ASkyBlock v3.0.6.4 generated an exception while executing task 199617
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 16
        at org.bukkit.craftbukkit.v1_8_R3.CraftChunkSnapshot.getBlockTypeId(CraftChunkSnapshot.java:56)
        at com.wasteofplastic.askyblock.SafeSpotTeleport$1.checkBlock(SafeSpotTeleport.java:267)
        at com.wasteofplastic.askyblock.SafeSpotTeleport$1.run(SafeSpotTeleport.java:158)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more
```

```>ver
[17:43:38 INFO]: This server is running CraftBukkit version git-TacoSpigot-"65fd35f" (MC: 1.8.8) (Implementing API version 1.8.8-R0.2-SNAPSHOT)
[17:43:38 INFO]: Checking version, please wait...
```

**Comment by tastybento** [comment]
This is when a player tried to teleport to a location at the top of the world. e.g., y=255

**Comment by tastybento** [comment]
Will be in 3.0.6.5.
