### ISSUE TITLE
Error when executing /asadmin settingsreset MOB_SPAWN

### ISSUE THREAD

**Issue by Poslovitch** [tastybento/ASkyBlock-Bugs-N-Features#183]
https://www.spigotmc.org/threads/askyblock.30325/page-196#post-2397891

Getting error when executing /asadmin settingsreset MOB_SPAWN
(Poslovitch's Note: might happen with every settings)

[05:27:05 INFO]: Protection settings being reset, please wait...
[05:27:05 WARN]: Exception in thread "Craft Scheduler Thread - 223"
[05:27:05 WARN]: org.apache.commons.lang.UnhandledException: Plugin ASkyBlock v3.0.6.4 generated an exception while executing task 68732
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
at com.wasteofplastic.askyblock.commands.AdminCmd$5.run(AdminCmd.java:998)
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
... 3 more

**Comment by tastybento** [comment]
Pretty sure this is related to #184 and #170

**Comment by tastybento** [comment]
Will be in 3.0.6.5.
