### ISSUE TITLE
Control Panel Not Working

### ISSUE THREAD

**Issue by benjamin7006** [tastybento/ASkyBlock-Bugs-N-Features#255]
Hello When Ever I Use The Control Panel On aSkyblock I Get An Error Everytime And Sometimes Other Users Get An Error Doing /is
I'll Paste My Error I'm Getting
```org.bukkit.command.CommandException: Unhandled exception executing command 'island' in plugin ASkyBlock v3.0.6.8
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-7d15d07-c194444]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-7d15d07-c194444]
	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServer.java:645) ~[spigot.jar:git-Spigot-7d15d07-c194444]
	at net.minecraft.server.v1_9_R1.PlayerConnection.handleCommand(PlayerConnection.java:1302) [spigot.jar:git-Spigot-7d15d07-c194444]
	at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1137) [spigot.jar:git-Spigot-7d15d07-c194444]
	at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-7d15d07-c194444]
	at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-7d15d07-c194444]
	at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-7d15d07-c194444]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131]
	at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [spigot.jar:git-Spigot-7d15d07-c194444]
	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:716) [spigot.jar:git-Spigot-7d15d07-c194444]
	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot.jar:git-Spigot-7d15d07-c194444]
	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:655) [spigot.jar:git-Spigot-7d15d07-c194444]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:554) [spigot.jar:git-Spigot-7d15d07-c194444]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.NullPointerException
	at org.bukkit.craftbukkit.v1_9_R1.entity.CraftHumanEntity.openInventory(CraftHumanEntity.java:178) ~[spigot.jar:git-Spigot-7d15d07-c194444]
	at com.wasteofplastic.askyblock.commands.IslandCmd.onCommand(IslandCmd.java:1386) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-7d15d07-c194444]
	... 15 more` < So

**Comment by tastybento** [comment]
Please pastebin.com your controlpanel.yml file and share the link. There is something odd in it.

**Comment by benjamin7006** [comment]
I Found The Problem, It Did Not Generate (controlpanel.yml)

**Comment by benjamin7006** [comment]
Oh And Also The Challenges Are Not Working
