### ISSUE TITLE
"An Internal Error Occured While Executing Your Command."

### ISSUE THREAD

**Issue by peterepro** [tastybento/ASkyBlock-Bugs-N-Features#267]
Every time I write a command, this message comes up. Any ideas?
My server has the following plugins:
Askyblock
Autosaveworld
Bstats
BukkitColors
ChatControl
ChestShop
ClearLag
EasyGui
Essentials
Group Manager
Luckperms
McMoney
META-INF (I think this is something random)
Multiverse-Core
MultiWorld
PermissionsEx
PluginMetrics
PowerRanks
ProtocolLib (not working on my server-not sure why I have it)
qQuests (not working)
SetSpawn
SimpleHomes
SkyblockEssentials
TPA
Updater
Vault
VoidGenerator
VoidSpawn
World
WorldEdit
WorldGuard
I am running 1.1.2.
Command Prompt:
```
52:08 [SEVERE] Exception while executing command: /island
org.bukkit.command.CommandException: Unhandled exception executing command 'island' in plugin ASkyBlock v3.0.6.8
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46)
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:188)
at net.glowstone.GlowServer.dispatchCommand(GlowServer.java:1362)
at net.glowstone.entity.GlowPlayer.lambda$chat$14(GlowPlayer.java:1797)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at net.glowstone.scheduler.GlowTask.run(GlowTask.java:167)
at net.glowstone.scheduler.GlowScheduler.pulse(GlowScheduler.java:152)
at net.glowstone.scheduler.GlowScheduler.lambda$start$0(GlowScheduler.java:83)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
at com.wasteofplastic.askyblock.commands.IslandCmd.chooseIsland(IslandCmd.java:3140)
at com.wasteofplastic.askyblock.commands.IslandCmd.onCommand(IslandCmd.java:1070)
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
... 15 more

**Comment by Poslovitch** [comment]
@peterepro Did you do a /reload? Does this error happen really every time you type any command starting with "/is" ?

@tastybento Seems to be caused by a null instance of SchematicsPanel returned by getSchematicsPanel().
https://github.com/tastybento/askyblock/blob/3.0.6.9/src/com/wasteofplastic/askyblock/commands/IslandCmd.java#L3140

**Comment by peterepro** [comment]
@Poslovitch @tastybento I have reloaded it multiple times with no luck. It occurs with every /is command. Any suggestions?

**Comment by tastybento** [comment]
@peterepro The error you reported is caused by the schematics selection GUI not being available/initialized. If you ay it happens with every /is command, I'd like to see the console errors for them, because I expect they'll be different. Note that instead of using /reload, you should be starting/stopping your server. Also, you should check for errors in the console log when you start up. Finally, do /asadmin reload and tell me what it says. Use pastebin.com to paste logs so we can see them.

**Comment by peterepro** [comment]
@Poslovitch @tastybento I apologize for the late response. Although I included what the command prompt said in Pastebin, /asadmin reload just did the same, "An internal error occurred while executing your command." How do I fix that error you mentioned? I tested all the /island commands and the link to the prompt is https://pastebin.com/WcWuZUu8 thanks so much!

**Comment by peterepro** [comment]
@Poslovitch @tastybento I forgot to mention it, but the linked prompt is from the server startup all the way through the commands.

**Comment by tastybento** [comment]
You are trying to make the plugins run on Glowstone and it's just not able to handle them. Switch to Spigot instead.
