### ISSUE TITLE
Askiblock and Acid Island not working after 1.12 change

### ISSUE THREAD

**Issue by M37AU** [tastybento/ASkyBlock-Bugs-N-Features#270]
Sorry to be a pest...
After the server upgraded to 1.12 the /IS and /AI commands (or any island plugin commands for that matter) don't error but don't work, I put the server back on 1.11.2 and they work again, nothing lost or altered apart from the achievements getting reset.
Where should I start looking to correct the fault?
Thanks

Regards - M37AU

**Comment by Poslovitch** [comment]
Were there errors in console? (If so, paste them here)

ASkyBlock has only a basic 1.12 pre release support, but I saw that other servers switched to 1.12 without encountering any problems. What plugins are you using?

**Comment by M37AU** [comment]
I think? this is what you're after and Multiverse seems to be the issue, can you help with this?
(Do you need the full log? It's a bit long to paste)

[01:31:48] [Server thread/INFO]: Trying to register generator with Multiverse 
[01:31:48] [Server thread/ERROR]: Not successfull! Disabling ASkyBlock!
[01:31:48] [Server thread/WARN]: org.bukkit.command.CommandException: Unhandled exception executing command 'mv' in plugin Multiverse-Core v2.4-b527
[01:31:48] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46)
[01:31:48] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[01:31:48] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:644)
[01:31:48] [Server thread/WARN]: 	at com.wasteofplastic.askyblock.ASkyBlock.getIslandWorld(ASkyBlock.java:163)
[01:31:48] [Server thread/WARN]: 	at com.wasteofplastic.askyblock.ASkyBlock$1.run(ASkyBlock.java:372)
[01:31:48] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71)
[01:31:48] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353)
[01:31:48] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:738)
[01:31:48] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405)
[01:31:48] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678)
[01:31:48] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576)
[01:31:48] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[01:31:48] [Server thread/WARN]: Caused by: java.lang.NullPointerException
[01:31:48] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.MultiverseCore.onCommand(MultiverseCore.java:476)
[01:31:48] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[01:31:48] [Server thread/WARN]: 	... 11 more
[01:31:48] [Server thread/INFO]: [ASkyBlock] Disabling ASkyBlock v3.0.6.8



[01:31:48] [Server thread/INFO]: Trying to register generator with Multiverse 
[01:31:48] [Server thread/ERROR]: Not successfull! Disabling ASkyBlock!
[01:31:48] [Server thread/WARN]: org.bukkit.command.CommandException: Unhandled exception executing command 'mv' in plugin Multiverse-Core v2.4-b527
[01:31:48] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46)
[01:31:48] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[01:31:48] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:644)
[01:31:48] [Server thread/WARN]: 	at com.wasteofplastic.askyblock.ASkyBlock.getIslandWorld(ASkyBlock.java:163)
[01:31:48] [Server thread/WARN]: 	at com.wasteofplastic.askyblock.ASkyBlock$1.run(ASkyBlock.java:372)
[01:31:48] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71)
[01:31:48] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353)
[01:31:48] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:738)
[01:31:48] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405)
[01:31:48] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678)
[01:31:48] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576)
[01:31:48] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[01:31:48] [Server thread/WARN]: Caused by: java.lang.NullPointerException
[01:31:48] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.MultiverseCore.onCommand(MultiverseCore.java:476)
[01:31:48] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[01:31:48] [Server thread/WARN]: 	... 11 more
[01:31:48] [Server thread/INFO]: [ASkyBlock] Disabling ASkyBlock v3.0.6.8

**Comment by M37AU** [comment]
OK, reloaded Multiverse-Core, that part of the problem is solved....
Thanks

Regards - M37AU
