### ISSUE TITLE
NullPointerException when executing "/is"

### ISSUE THREAD

**Issue by Poslovitch** [tastybento/ASkyBlock-Bugs-N-Features#274]
```[15:55:15] [Server thread/INFO]: FullVaasic issued server command: /is
[15:55:15] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'is' in plugin ASkyBlock v3.0.6.8
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[Spigot.jar:git-Spigot-de459a2-51263e9]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[Spigot.jar:git-Spigot-de459a2-51263e9]
	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:647) ~[Spigot.jar:git-Spigot-de459a2-51263e9]
	at net.minecraft.server.v1_10_R1.PlayerConnection.handleCommand(PlayerConnection.java:1358) [Spigot.jar:git-Spigot-de459a2-51263e9]
	at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1193) [Spigot.jar:git-Spigot-de459a2-51263e9]
	at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [Spigot.jar:git-Spigot-de459a2-51263e9]
	at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [Spigot.jar:git-Spigot-de459a2-51263e9]
	at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [Spigot.jar:git-Spigot-de459a2-51263e9]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131]
	at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [Spigot.jar:git-Spigot-de459a2-51263e9]
	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:732) [Spigot.jar:git-Spigot-de459a2-51263e9]
	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) [Spigot.jar:git-Spigot-de459a2-51263e9]
	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) [Spigot.jar:git-Spigot-de459a2-51263e9]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [Spigot.jar:git-Spigot-de459a2-51263e9]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: org.bukkit.command.CommandException: Unhandled exception executing command 'island' in plugin ASkyBlock v3.0.6.8
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[Spigot.jar:git-Spigot-de459a2-51263e9]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[Spigot.jar:git-Spigot-de459a2-51263e9]
	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:647) ~[Spigot.jar:git-Spigot-de459a2-51263e9]
	at org.bukkit.craftbukkit.v1_10_R1.entity.CraftPlayer.performCommand(CraftPlayer.java:243) ~[Spigot.jar:git-Spigot-de459a2-51263e9]
	at com.wasteofplastic.askyblock.commands.IslandCmd.onCommand(IslandCmd.java:1076) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[Spigot.jar:git-Spigot-de459a2-51263e9]
	... 15 more
Caused by: java.lang.NullPointerException
	at org.bukkit.craftbukkit.v1_10_R1.entity.CraftHumanEntity.openInventory(CraftHumanEntity.java:183) ~[Spigot.jar:git-Spigot-de459a2-51263e9]
	at com.wasteofplastic.askyblock.commands.IslandCmd.onCommand(IslandCmd.java:1386) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[Spigot.jar:git-Spigot-de459a2-51263e9]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[Spigot.jar:git-Spigot-de459a2-51263e9]
	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:647) ~[Spigot.jar:git-Spigot-de459a2-51263e9]
	at org.bukkit.craftbukkit.v1_10_R1.entity.CraftPlayer.performCommand(CraftPlayer.java:243) ~[Spigot.jar:git-Spigot-de459a2-51263e9]
	at com.wasteofplastic.askyblock.commands.IslandCmd.onCommand(IslandCmd.java:1076) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[Spigot.jar:git-Spigot-de459a2-51263e9]
	... 15 more`

**Comment by tastybento** [comment]
The control panel yml is missing the default panel section. Delete the yml file and let it get regenerated and then edit it again. The root cause is that the default panel name is nothing because it is missing. This causes the panel to be null.

**Comment by Poslovitch** [comment]
I will add a null-check to avoid further reports.

**Comment by Poslovitch** [comment]
Well, the way ControlPanel is handled is a bit strange. As it is a non-major bug and because of the rewriting of the panels in BSkyblock, I decline this bug request.
