### ISSUE TITLE
Constant Console Errors bug?

### ISSUE THREAD

**Issue by KingGoldensPanda** [tastybento/ASkyBlock-Bugs-N-Features#329]
[17:38:41 ERROR]: Could not pass event PlayerTeleportEvent to ASkyBlock v3.0.6.9
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-7228328-11323bf]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-7228328-11323bf]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [spigot.jar:git-Spigot-7228328-11323bf]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot.jar:git-Spigot-7228328-11323bf]
        at org.bukkit.craftbukkit.v1_12_R1.entity.CraftPlayer.teleport(CraftPlayer.java:482) [spigot.jar:git-Spigot-7228328-11323bf]
        at com.earth2me.essentials.Teleport.now(Teleport.java:127) [EssentialsX-2.0.1.jar:?]
        at com.earth2me.essentials.TimedTeleport$1DelayedTeleportTask.run(TimedTeleport.java:109) [EssentialsX-2.0.1.jar:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) [spigot.jar:git-Spigot-7228328-11323bf]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot.jar:git-Spigot-7228328-11323bf]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:738) [spigot.jar:git-Spigot-7228328-11323bf]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [spigot.jar:git-Spigot-7228328-11323bf]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot.jar:git-Spigot-7228328-11323bf]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot.jar:git-Spigot-7228328-11323bf]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]

[17:39:32 ERROR]: Could not pass event PlayerTeleportEvent to ASkyBlock v3.0.6.9
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-7228328-11323bf]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-7228328-11323bf]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [spigot.jar:git-Spigot-7228328-11323bf]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot.jar:git-Spigot-7228328-11323bf]
        at org.bukkit.craftbukkit.v1_12_R1.entity.CraftPlayer.teleport(CraftPlayer.java:482) [spigot.jar:git-Spigot-7228328-11323bf]
        at org.bukkit.craftbukkit.v1_12_R1.entity.CraftEntity.teleport(CraftEntity.java:271) [spigot.jar:git-Spigot-7228328-11323bf]
        at com.wasteofplastic.askyblock.GridManager.homeTeleport(GridManager.java:1261) [askyblock.jar:?]
        at com.wasteofplastic.askyblock.GridManager.homeTeleport(GridManager.java:1228) [askyblock.jar:?]
        at com.wasteofplastic.askyblock.commands.IslandCmd.onCommand(IslandCmd.java:1080) [askyblock.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [spigot.jar:git-Spigot-7228328-11323bf]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot.jar:git-Spigot-7228328-11323bf]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:644) [spigot.jar:git-Spigot-7228328-11323bf]
        at org.bukkit.craftbukkit.v1_12_R1.entity.CraftPlayer.performCommand(CraftPlayer.java:246) [spigot.jar:git-Spigot-7228328-11323bf]
        at com.wasteofplastic.askyblock.panels.ControlPanel.onInventoryClick(ControlPanel.java:419) [askyblock.jar:?]
        at sun.reflect.GeneratedMethodAccessor377.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) [spigot.jar:git-Spigot-7228328-11323bf]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot.jar:git-Spigot-7228328-11323bf]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [spigot.jar:git-Spigot-7228328-11323bf]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot.jar:git-Spigot-7228328-11323bf]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1877) [spigot.jar:git-Spigot-7228328-11323bf]
        at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:33) [spigot.jar:git-Spigot-7228328-11323bf]
        at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:10) [spigot.jar:git-Spigot-7228328-11323bf]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-7228328-11323bf]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot.jar:git-Spigot-7228328-11323bf]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:747) [spigot.jar:git-Spigot-7228328-11323bf]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [spigot.jar:git-Spigot-7228328-11323bf]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot.jar:git-Spigot-7228328-11323bf]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot.jar:git-Spigot-7228328-11323bf]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.NullPointerException

[10:07:16 WARN]: [ASkyBlock] Task #189171 for ASkyBlock v3.0.6.9 generated an exception
java.lang.NullPointerException: null
        at com.wasteofplastic.askyblock.TinyDB.savePlayerName(TinyDB.java:199) ~[?:?]
        at com.wasteofplastic.askyblock.PlayerCache.save(PlayerCache.java:495) ~[?:?]
        at com.wasteofplastic.askyblock.ASkyBlock.resetPlayer(ASkyBlock.java:763) ~[?:?]
        at com.wasteofplastic.askyblock.schematics.Schematic$1.run(Schematic.java:1062) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-7228328-11323bf]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot.jar:git-Spigot-7228328-11323bf]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:738) [spigot.jar:git-Spigot-7228328-11323bf]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [spigot.jar:git-Spigot-7228328-11323bf]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot.jar:git-Spigot-7228328-11323bf]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot.jar:git-Spigot-7228328-11323bf]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]

[10:07:17 WARN]: [ASkyBlock] Task #190095 for ASkyBlock v3.0.6.9 generated an exception
java.lang.NullPointerException: null
        at com.wasteofplastic.askyblock.TinyDB.savePlayerName(TinyDB.java:199) ~[?:?]
        at com.wasteofplastic.askyblock.PlayerCache.save(PlayerCache.java:495) ~[?:?]
        at com.wasteofplastic.askyblock.LevelCalcByChunk$1$1.run(LevelCalcByChunk.java:412) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-7228328-11323bf]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot.jar:git-Spigot-7228328-11323bf]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:738) [spigot.jar:git-Spigot-7228328-11323bf]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [spigot.jar:git-Spigot-7228328-11323bf]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot.jar:git-Spigot-7228328-11323bf]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot.jar:git-Spigot-7228328-11323bf]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]

[10:07:17 WARN]: [ASkyBlock] Task #190102 for ASkyBlock v3.0.6.9 generated an exception
java.lang.NullPointerException: null
        at com.wasteofplastic.askyblock.TinyDB.savePlayerName(TinyDB.java:199) ~[?:?]
        at com.wasteofplastic.askyblock.PlayerCache.save(PlayerCache.java:495) ~[?:?]
        at com.wasteofplastic.askyblock.LevelCalcByChunk$1$1.run(LevelCalcByChunk.java:412) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-7228328-11323bf]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot.jar:git-Spigot-7228328-11323bf]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:738) [spigot.jar:git-Spigot-7228328-11323bf]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [spigot.jar:git-Spigot-7228328-11323bf]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot.jar:git-Spigot-7228328-11323bf]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot.jar:git-Spigot-7228328-11323bf]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]

[10:07:17 WARN]: [ASkyBlock] Task #190119 for ASkyBlock v3.0.6.9 generated an exception
java.lang.NullPointerException: null
        at com.wasteofplastic.askyblock.TinyDB.savePlayerName(TinyDB.java:199) ~[?:?]
        at com.wasteofplastic.askyblock.PlayerCache.save(PlayerCache.java:495) ~[?:?]
        at com.wasteofplastic.askyblock.LevelCalcByChunk$1$1.run(LevelCalcByChunk.java:412) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-7228328-11323bf]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot.jar:git-Spigot-7228328-11323bf]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:738) [spigot.jar:git-Spigot-7228328-11323bf]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [spigot.jar:git-Spigot-7228328-11323bf]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot.jar:git-Spigot-7228328-11323bf]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot.jar:git-Spigot-7228328-11323bf]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]

**Comment by tastybento** [comment]
The error is being caused by a player somehow having a null name. Do you have any custom entities or NPC's?

**Comment by tastybento** [comment]
No answer from @KingGoldensPanda
