### ISSUE TITLE
java.lang.NullPointerException at com.wasteofplastic.askyblock.schematics.Schematic.<init>(Schematic.java:410)

### ISSUE THREAD

**Issue by TheSnoozer** [tastybento/ASkyBlock-Bugs-N-Features#340]
Hi, i was trying to use a custom schematic for an island and ran into a NPE-Exception.
The schematic can be loaded and pasted in by world-downloader; not sure what could be wrong here.

```
[17:47:29 INFO]: Starting minecraft server version 1.8.8
....
[17:47:29 INFO]: This server is running CraftBukkit version git-PaperSpigot-"4c7641d" (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
....
[17:47:31 INFO]: [ASkyBlock] Loaded default island schematic.
[17:47:31 WARN]: Spawner setting of WITHER_SKELETON is unknown for this server. Skipping.
[17:47:31 INFO]: [ASkyBlock] Loaded default nether schematic.
[17:47:32 INFO]: [ASkyBlock] Loading schematic The Original (island.schematic) for all players, order 1
[17:47:32 WARN]: Spawner setting of WITHER_SKELETON is unknown for this server. Skipping.
[17:47:32 INFO]: [ASkyBlock] Loading schematic NetherBlock Island (nether.schematic) for all players, order 2
[17:47:32 INFO]: [ASkyBlock] Loading schematic Island Duo (double.schematic) for all players, order 2
[17:47:32 INFO]: [ASkyBlock] Loading schematic §lBlack §bDiamonds (harder.schematic) for all players, order 3
[17:47:32 ERROR]: Error occurred while enabling ASkyBlock v3.0.6.9 (Is it up to date?)
java.lang.NullPointerException
	at com.wasteofplastic.askyblock.schematics.Schematic.<init>(Schematic.java:410) ~[?:?]
	at com.wasteofplastic.askyblock.commands.IslandCmd.loadSchematics(IslandCmd.java:276) ~[?:?]
	at com.wasteofplastic.askyblock.commands.IslandCmd.<init>(IslandCmd.java:129) ~[?:?]
	at com.wasteofplastic.askyblock.ASkyBlock.onEnable(ASkyBlock.java:328) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[paperspigot1.8.8.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [paperspigot1.8.8.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [paperspigot1.8.8.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359) [paperspigot1.8.8.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318) [paperspigot1.8.8.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:203) [paperspigot1.8.8.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [paperspigot1.8.8.jar:git-PaperSpigot-"4c7641d"]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
[17:47:32 INFO]: [ASkyBlock] Disabling ASkyBlock v3.0.6.9
```

**Comment by tastybento** [comment]
There's some entity in the file that doesn't have a location. Load the schematic with the latest version of WorldEdit and then copy and save it again. Then try.

**Comment by tastybento** [comment]
Could you share the schematic using dropbox or something? I'd like to look at it. Thanks.

**Comment by TheSnoozer** [comment]
Sure, not a problem. You can upload files to github as well ;-)
Here is a zip of the schematic-File (extract):
[example.zip](https://github.com/tastybento/ASkyBlock-Bugs-N-Features/files/1150167/example.zip)

Will test with worldedit again.

**Comment by tastybento** [comment]
I found the problem. There is no WEOrigin in the schematic, which is not surprising if it isn't a World Edit schematic. I fixed the code so that WEOrigin can be ignored if it doesn't exist. The fix will be in the next release. Thanks!

**Comment by tastybento** [comment]
Also, you'll need to use a spawn block to position the spawn position of the player with that schematic because the default safe position is underground!
