### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by baileyiscoolwow** [tastybento/ASkyBlock-Bugs-N-Features#363]
```
[01:51:27 INFO]: [ASkyBlock] Silencing command feedback for Ops...
[01:51:27 INFO]: Game rule sendCommandFeedback has been updated to false
[01:51:27 INFO]: [ASkyBlock] If you do not want this, do /gamerule sendCommandFeedback true
[01:51:27 INFO]: [ASkyBlock] Checking for new updates...
[01:51:27 INFO]: [Vault] Checking for Updates ...
[01:51:27 INFO]: [ASkyBlock] Loading island grid...
[01:51:27 INFO]: [ASkyBlock] islands.yml does not exist. Creating...
[01:51:27 INFO]: [ASkyBlock] Saving top ten list
[01:51:27 INFO]: [ASkyBlock] Saved top ten list
[01:51:27 INFO]: [ASkyBlock] islands.yml created.
[01:51:27 ERROR]: [ASkyBlock] Plugin ASkyBlock v3.0.6.9 has failed to register events for class com.wasteofplastic.askyblock.listeners.IslandGuard1_9 because org/bukkit/event/entity/LingeringPotionSplashEvent does not exist.
[01:51:27 INFO]: [ASkyBlock] Loading warps...
[01:51:27 INFO]: [ASkyBlock] No warps.yml found. Creating it...
[01:51:27 INFO]: [ASkyBlock] No minishop.yml found. Creating it...
[01:51:27 INFO]: [ASkyBlock] Using default found in jar file.
[01:51:27 WARN]: [ASkyBlock] Task #406 for ASkyBlock v3.0.6.9 generated an exception
java.lang.NoClassDefFoundError: org/bukkit/potion/PotionData
        at com.wasteofplastic.askyblock.commands.Challenges.getPotion(Challenges.java:676) ~[?:?]
        at com.wasteofplastic.askyblock.panels.MiniShopItem.<init>(MiniShopItem.java:109) ~[?:?]
        at com.wasteofplastic.askyblock.panels.ControlPanel.loadShop(ControlPanel.java:126) ~[?:?]
        at com.wasteofplastic.askyblock.panels.ControlPanel.<init>(ControlPanel.java:66) ~[?:?]
        at com.wasteofplastic.askyblock.ASkyBlock$1$1.run(ASkyBlock.java:436) ~[?:?]
        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-7d15d07-c194444]
        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-7d15d07-c194444]
        at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:724) [spigot.jar:git-Spigot-7d15d07-c194444]
        at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot.jar:git-Spigot-7d15d07-c194444]
        at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:655) [spigot.jar:git-Spigot-7d15d07-c194444]
        at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:554) [spigot.jar:git-Spigot-7d15d07-c194444]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]
Caused by: java.lang.ClassNotFoundException: org.bukkit.potion.PotionData
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91) ~[spigot.jar:git-Spigot-7d15d07-c194444]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot.jar:git-Spigot-7d15d07-c194444]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_91]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_91]
        ... 12 more
[01:51:27 INFO]: Complete. Processed 0 names to database
[01:51:27 INFO]: [ASkyBlock] No update available.
[01:51:27 INFO]: [Vault] No new version available
[01:51:28 INFO]: [PlaceholderAPI] 79 placeholder expansions are available on the cloud.
[01:51:28 INFO]: [PlaceholderAPI] 0 expansions you use have updates.
[01:52:04 INFO]: UUID of player SirBailey is 47fbea56-c5f1-469b-8fe2-50aa52a24afe
[01:52:05 ERROR]: Could not pass event PlayerTeleportEvent to ASkyBlock v3.0.6.9
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-7d15d07-c194444]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-7d15d07-c194444]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-7d15d07-c194444]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-7d15d07-c194444]
        at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:642) [spigot.jar:git-Spigot-7d15d07-c194444]
        at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:610) [spigot.jar:git-Spigot-7d15d07-c194444]
        at net.minecraft.server.v1_9_R1.PlayerList.a(PlayerList.java:161) [spigot.jar:git-Spigot-7d15d07-c194444]
        at net.minecraft.server.v1_9_R1.LoginListener.b(LoginListener.java:144) [spigot.jar:git-Spigot-7d15d07-c194444]
        at net.minecraft.server.v1_9_R1.LoginListener.c(LoginListener.java:54) [spigot.jar:git-Spigot-7d15d07-c194444]
        at net.minecraft.server.v1_9_R1.NetworkManager.a(NetworkManager.java:232) [spigot.jar:git-Spigot-7d15d07-c194444]
        at net.minecraft.server.v1_9_R1.ServerConnection.c(ServerConnection.java:141) [spigot.jar:git-Spigot-7d15d07-c194444]
        at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:815) [spigot.jar:git-Spigot-7d15d07-c194444]
        at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot.jar:git-Spigot-7d15d07-c194444]
        at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:655) [spigot.jar:git-Spigot-7d15d07-c194444]
        at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:554) [spigot.jar:git-Spigot-7d15d07-c194444]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]
Caused by: java.lang.NoSuchFieldError: CHORUS_FRUIT
        at com.wasteofplastic.askyblock.listeners.PlayerEvents.onPlayerTeleport(PlayerEvents.java:671) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_91]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-7d15d07-c194444]
        ... 15 more
[01:52:05 INFO]: SirBailey[/127.0.0.1:61979] logged in with entity id 0 at ([ASkyBlock]0.5, 120.0, 2.5)
[01:52:09 INFO]: SirBailey issued server command: /spawn
[01:52:09 ERROR]: Could not pass event PlayerTeleportEvent to ASkyBlock v3.0.6.9
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-7d15d07-c194444]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-7d15d07-c194444]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-7d15d07-c194444]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-7d15d07-c194444]
        at org.bukkit.craftbukkit.v1_9_R1.entity.CraftPlayer.teleport(CraftPlayer.java:445) [spigot.jar:git-Spigot-7d15d07-c194444]
        at com.earth2me.essentials.Teleport.now(Teleport.java:139) [Essentials.jar:?]
        at com.earth2me.essentials.Teleport.teleport(Teleport.java:198) [Essentials.jar:?]
        at com.earth2me.essentials.Teleport.teleportPlayer(Teleport.java:168) [Essentials.jar:?]
        at com.earth2me.essentials.spawn.Commandspawn.respawn(Commandspawn.java:56) [EssentialsSpawn.jar:?]
        at com.earth2me.essentials.spawn.Commandspawn.run(Commandspawn.java:33) [EssentialsSpawn.jar:?]
        at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:157) [Essentials.jar:?]
        at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:511) [Essentials.jar:?]
        at com.earth2me.essentials.spawn.EssentialsSpawn.onCommand(EssentialsSpawn.java:64) [EssentialsSpawn.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [spigot.jar:git-Spigot-7d15d07-c194444]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot.jar:git-Spigot-7d15d07-c194444]
        at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServer.java:645) [spigot.jar:git-Spigot-7d15d07-c194444]
        at net.minecraft.server.v1_9_R1.PlayerConnection.handleCommand(PlayerConnection.java:1302) [spigot.jar:git-Spigot-7d15d07-c194444]
        at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1137) [spigot.jar:git-Spigot-7d15d07-c194444]
        at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-7d15d07-c194444]
        at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-7d15d07-c194444]
        at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-7d15d07-c194444]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_91]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_91]
        at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [spigot.jar:git-Spigot-7d15d07-c194444]
        at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:716) [spigot.jar:git-Spigot-7d15d07-c194444]
        at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot.jar:git-Spigot-7d15d07-c194444]
        at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:655) [spigot.jar:git-Spigot-7d15d07-c194444]
        at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:554) [spigot.jar:git-Spigot-7d15d07-c194444]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]
Caused by: java.lang.NoSuchFieldError: CHORUS_FRUIT
        at com.wasteofplastic.askyblock.listeners.PlayerEvents.onPlayerTeleport(PlayerEvents.java:671) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_91]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-7d15d07-c194444]
        ... 28 more
[01:52:14 INFO]: SirBailey lost connection: Disconnected
[01:52:14 INFO]: SirBailey left the game.
[01:52:17 INFO]: UUID of player SirBailey is 47fbea56-c5f1-469b-8fe2-50aa52a24afe
[01:52:17 INFO]: SirBailey[/127.0.0.1:61987] logged in with entity id 24 at ([world]112.12754753692076, 98.0, 100.45352284464752)
[01:52:21 INFO]: SirBailey issued server command: /is
[01:52:23 ERROR]: Could not pass event PlayerTeleportEvent to ASkyBlock v3.0.6.9
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-7d15d07-c194444]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-7d15d07-c194444]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-7d15d07-c194444]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-7d15d07-c194444]
        at org.bukkit.craftbukkit.v1_9_R1.entity.CraftPlayer.teleport(CraftPlayer.java:445) [spigot.jar:git-Spigot-7d15d07-c194444]
        at org.bukkit.craftbukkit.v1_9_R1.entity.CraftEntity.teleport(CraftEntity.java:228) [spigot.jar:git-Spigot-7d15d07-c194444]
        at com.wasteofplastic.askyblock.GridManager.homeTeleport(GridManager.java:1261) [askyblock.jar:?]
        at com.wasteofplastic.askyblock.GridManager.homeTeleport(GridManager.java:1228) [askyblock.jar:?]
        at com.wasteofplastic.askyblock.schematics.Schematic$1.run(Schematic.java:1059) [askyblock.jar:?]
        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:71) [spigot.jar:git-Spigot-7d15d07-c194444]
        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-7d15d07-c194444]
        at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:724) [spigot.jar:git-Spigot-7d15d07-c194444]
        at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot.jar:git-Spigot-7d15d07-c194444]
        at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:655) [spigot.jar:git-Spigot-7d15d07-c194444]
        at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:554) [spigot.jar:git-Spigot-7d15d07-c194444]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]
Caused by: java.lang.NoSuchFieldError: CHORUS_FRUIT
        at com.wasteofplastic.askyblock.listeners.PlayerEvents.onPlayerTeleport(PlayerEvents.java:671) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_91]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-7d15d07-c194444]
        ... 15 more
[01:52:23 INFO]: Title command successfully executed
[01:52:23 INFO]: Title command successfully executed
[01:52:41 INFO]: SirBailey issued server command: /spawn
[01:52:41 ERROR]: Could not pass event PlayerTeleportEvent to ASkyBlock v3.0.6.9
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-7d15d07-c194444]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-7d15d07-c194444]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-7d15d07-c194444]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-7d15d07-c194444]
        at org.bukkit.craftbukkit.v1_9_R1.entity.CraftPlayer.teleport(CraftPlayer.java:445) [spigot.jar:git-Spigot-7d15d07-c194444]
        at com.earth2me.essentials.Teleport.now(Teleport.java:139) [Essentials.jar:?]
        at com.earth2me.essentials.Teleport.teleport(Teleport.java:198) [Essentials.jar:?]
        at com.earth2me.essentials.Teleport.teleportPlayer(Teleport.java:168) [Essentials.jar:?]
        at com.earth2me.essentials.spawn.Commandspawn.respawn(Commandspawn.java:56) [EssentialsSpawn.jar:?]
        at com.earth2me.essentials.spawn.Commandspawn.run(Commandspawn.java:33) [EssentialsSpawn.jar:?]
        at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:157) [Essentials.jar:?]
        at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:511) [Essentials.jar:?]
        at com.earth2me.essentials.spawn.EssentialsSpawn.onCommand(EssentialsSpawn.java:64) [EssentialsSpawn.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [spigot.jar:git-Spigot-7d15d07-c194444]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot.jar:git-Spigot-7d15d07-c194444]
        at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServer.java:645) [spigot.jar:git-Spigot-7d15d07-c194444]
        at net.minecraft.server.v1_9_R1.PlayerConnection.handleCommand(PlayerConnection.java:1302) [spigot.jar:git-Spigot-7d15d07-c194444]
        at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1137) [spigot.jar:git-Spigot-7d15d07-c194444]
        at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-7d15d07-c194444]
        at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-7d15d07-c194444]
        at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-7d15d07-c194444]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_91]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_91]
        at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [spigot.jar:git-Spigot-7d15d07-c194444]
        at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:716) [spigot.jar:git-Spigot-7d15d07-c194444]
        at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot.jar:git-Spigot-7d15d07-c194444]
        at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:655) [spigot.jar:git-Spigot-7d15d07-c194444]
        at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:554) [spigot.jar:git-Spigot-7d15d07-c194444]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]
Caused by: java.lang.NoSuchFieldError: CHORUS_FRUIT
        at com.wasteofplastic.askyblock.listeners.PlayerEvents.onPlayerTeleport(PlayerEvents.java:671) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_91]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-7d15d07-c194444]
        ... 28 more
[01:52:44 INFO]: SirBailey lost connection: Disconnected
[01:52:44 INFO]: SirBailey left the game.
[01:52:46 INFO]: UUID of player SirBailey is 47fbea56-c5f1-469b-8fe2-50aa52a24afe
[01:52:46 INFO]: SirBailey[/127.0.0.1:62040] logged in with entity id 96 at ([world]101.5, 100.0, 100.5)
[01:52:50 INFO]: SirBailey issued server command: /is
[01:52:50 ERROR]: Could not pass event PlayerTeleportEvent to ASkyBlock v3.0.6.9
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-7d15d07-c194444]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-7d15d07-c194444]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-7d15d07-c194444]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-7d15d07-c194444]
        at org.bukkit.craftbukkit.v1_9_R1.entity.CraftPlayer.teleport(CraftPlayer.java:445) [spigot.jar:git-Spigot-7d15d07-c194444]
        at org.bukkit.craftbukkit.v1_9_R1.entity.CraftEntity.teleport(CraftEntity.java:228) [spigot.jar:git-Spigot-7d15d07-c194444]
        at com.wasteofplastic.askyblock.GridManager.homeTeleport(GridManager.java:1261) [askyblock.jar:?]
        at com.wasteofplastic.askyblock.GridManager.homeTeleport(GridManager.java:1228) [askyblock.jar:?]
        at com.wasteofplastic.askyblock.commands.IslandCmd.onCommand(IslandCmd.java:1080) [askyblock.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [spigot.jar:git-Spigot-7d15d07-c194444]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot.jar:git-Spigot-7d15d07-c194444]
        at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServer.java:645) [spigot.jar:git-Spigot-7d15d07-c194444]
        at net.minecraft.server.v1_9_R1.PlayerConnection.handleCommand(PlayerConnection.java:1302) [spigot.jar:git-Spigot-7d15d07-c194444]
        at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1137) [spigot.jar:git-Spigot-7d15d07-c194444]
        at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-7d15d07-c194444]
        at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-7d15d07-c194444]
        at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-7d15d07-c194444]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_91]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_91]
        at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [spigot.jar:git-Spigot-7d15d07-c194444]
        at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:716) [spigot.jar:git-Spigot-7d15d07-c194444]
        at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot.jar:git-Spigot-7d15d07-c194444]
        at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:655) [spigot.jar:git-Spigot-7d15d07-c194444]
        at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:554) [spigot.jar:git-Spigot-7d15d07-c194444]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]
Caused by: java.lang.NoSuchFieldError: CHORUS_FRUIT
        at com.wasteofplastic.askyblock.listeners.PlayerEvents.onPlayerTeleport(PlayerEvents.java:671) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_91]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-7d15d07-c194444]
        ... 24 more
[01:52:53 INFO]: SirBailey lost connection: Disconnected
[01:52:53 INFO]: SirBailey left the game.
[01:52:56 INFO]: UUID of player SirBailey is 47fbea56-c5f1-469b-8fe2-50aa52a24afe
[01:52:56 ERROR]: Could not pass event PlayerTeleportEvent to ASkyBlock v3.0.6.9
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-7d15d07-c194444]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-7d15d07-c194444]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-7d15d07-c194444]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-7d15d07-c194444]
        at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:642) [spigot.jar:git-Spigot-7d15d07-c194444]
        at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:610) [spigot.jar:git-Spigot-7d15d07-c194444]
        at net.minecraft.server.v1_9_R1.PlayerList.a(PlayerList.java:161) [spigot.jar:git-Spigot-7d15d07-c194444]
        at net.minecraft.server.v1_9_R1.LoginListener.b(LoginListener.java:144) [spigot.jar:git-Spigot-7d15d07-c194444]
        at net.minecraft.server.v1_9_R1.LoginListener.c(LoginListener.java:54) [spigot.jar:git-Spigot-7d15d07-c194444]
        at net.minecraft.server.v1_9_R1.NetworkManager.a(NetworkManager.java:232) [spigot.jar:git-Spigot-7d15d07-c194444]
        at net.minecraft.server.v1_9_R1.ServerConnection.c(ServerConnection.java:141) [spigot.jar:git-Spigot-7d15d07-c194444]
        at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:815) [spigot.jar:git-Spigot-7d15d07-c194444]
        at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot.jar:git-Spigot-7d15d07-c194444]
        at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:655) [spigot.jar:git-Spigot-7d15d07-c194444]
        at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:554) [spigot.jar:git-Spigot-7d15d07-c194444]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]
Caused by: java.lang.NoSuchFieldError: CHORUS_FRUIT
        at com.wasteofplastic.askyblock.listeners.PlayerEvents.onPlayerTeleport(PlayerEvents.java:671) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_91]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-7d15d07-c194444]
        ... 15 more
[01:52:56 INFO]: SirBailey[/127.0.0.1:62067] logged in with entity id 116 at ([ASkyBlock]0.5, 120.0, 2.5)

**Comment by tastybento** [comment]
What server version are you using? It looks like 1.9. If so, upgrade to at least 1.9.2 or later, say like 1.12 and it'll work. With 1.9, the potion API wasn't implemented.
