### ISSUE TITLE
Cant create Island

### ISSUE THREAD

**Issue by DampfWaffel** [tastybento/ASkyBlock-Bugs-N-Features#378]
Hello,

I have the following problem:
I had recently exchanged my old schmetic and now when i create an Island, it is an normal Iceland or I get an error, but unfortunately I do not know what the Error is trying to to tell me.

https://hastebin.com/vibicuwumu.vbs

`[22:19:24 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'is' in plugin ASkyBlock v3.0.6.9
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:146) ~[patched.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:666) ~[patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1189) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1001) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [patched.jar:git-PaperSpigot-"4c7641d"]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_141]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_141]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched.jar:git-PaperSpigot-"4c7641d"]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_141]
Caused by: java.lang.NullPointerException
        at com.wasteofplastic.askyblock.commands.IslandCmd.newIsland(IslandCmd.java:713) ~[?:?]
        at com.wasteofplastic.askyblock.commands.IslandCmd.newIsland(IslandCmd.java:684) ~[?:?]
        at com.wasteofplastic.askyblock.commands.IslandCmd.chooseIsland(IslandCmd.java:3132) ~[?:?]
        at com.wasteofplastic.askyblock.commands.IslandCmd.onCommand(IslandCmd.java:1064) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched.jar:git-PaperSpigot-"4c7641d"]
        ... 15 more`
Version: CraftBukkit version git-PaperSpigot-"4c7641d" (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
Java 8

**Comment by Poslovitch** [comment]
Can you please send us the schematic you're using?

**Comment by DampfWaffel** [comment]
https://www.dropbox.com/s/czsxv5pxf3kah7s/default.schematic?dl=0

**Comment by tastybento** [comment]
Your config.yml is probably missing the "default" section in the schematics section. Paste your config.yml we can see it.

**Comment by DampfWaffel** [comment]
Okay, here is the Coinfig, hopefully you find something.
https://hastebin.com/ayatawexij.php

**Comment by DampfWaffel** [comment]
Found the Problem! i was so stupid that i don't look in that log.
I forgot to add the Bedrock
