### ISSUE TITLE
NPE with GridManager

### ISSUE THREAD

**Issue by CharlieIsHere** [tastybento/ASkyBlock-Bugs-N-Features#398]
**Server Software:** PaperSpigot 1.8.8
**ASkyBlock Version:** 3.0.6.11
**Console Exception:**
```
org.bukkit.event.EventException
Caused by: java.lang.NullPointerException
        at com.wasteofplastic.askyblock.GridManager.getIslandName(GridManager.java:1705)
        at com.wasteofplastic.askyblock.listeners.PlayerEvents.onPlayerTeleport(PlayerEvents.java:747)
```

**Comment by Poslovitch** [comment]
Can we have to full error report from `Caused by: java.lang.NullPointerException` ?

**Comment by tastybento** [comment]
This occurs when a player teleports to an unowned island that has been previously locked from a location that is not an island.
