### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by Manu5656** [tastybento/ASkyBlock-Bugs-N-Features#404]
How do I fix this problem?

`[04:25:21 INFO]: massbroking199 issued server command: /c
[04:25:22 ERROR]: Could not pass event PlayerInteractEvent to NotifyIslands v1.0
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[PaperSpigot.jar:git-PaperSpigot-fe4c7c8-d27e6d0]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[PaperSpigot.jar:git-PaperSpigot-fe4c7c8-d27e6d0]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [PaperSpigot.jar:git-PaperSpigot-fe4c7c8-d27e6d0]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [PaperSpigot.jar:git-PaperSpigot-fe4c7c8-d27e6d0]
        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:227) [PaperSpigot.jar:git-PaperSpigot-fe4c7c8-d27e6d0]
        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:194) [PaperSpigot.jar:git-PaperSpigot-fe4c7c8-d27e6d0]
        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:190) [PaperSpigot.jar:git-PaperSpigot-fe4c7c8-d27e6d0]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:721) [PaperSpigot.jar:git-PaperSpigot-fe4c7c8-d27e6d0]
        at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:52) [PaperSpigot.jar:git-PaperSpigot-fe4c7c8-d27e6d0]
        at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1) [PaperSpigot.jar:git-PaperSpigot-fe4c7c8-d27e6d0]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [PaperSpigot.jar:git-PaperSpigot-fe4c7c8-d27e6d0]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_141]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_141]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SystemUtils.java:19) [PaperSpigot.jar:git-PaperSpigot-fe4c7c8-d27e6d0]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:771) [PaperSpigot.jar:git-PaperSpigot-fe4c7c8-d27e6d0]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [PaperSpigot.jar:git-PaperSpigot-fe4c7c8-d27e6d0]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:710) [PaperSpigot.jar:git-PaperSpigot-fe4c7c8-d27e6d0]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:613) [PaperSpigot.jar:git-PaperSpigot-fe4c7c8-d27e6d0]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]
Caused by: java.lang.NumberFormatException: For input string: "§r§7Unbreaking II"
        at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043) ~[?:1.8.0_141]
        at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110) ~[?:1.8.0_141]
        at java.lang.Double.parseDouble(Double.java:538) ~[?:1.8.0_141]
        at java.lang.Double.<init>(Double.java:608) ~[?:1.8.0_141]
        at it.hylp.notify.events.assegnolisteners.onNoteClick(assegnolisteners.java:58) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor201.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_141]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_141]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[PaperSpigot.jar:git-PaperSpigot-fe4c7c8-d27e6d0]
        ... 18 more`

**Comment by Poslovitch** [comment]
This isn't ASkyBlock.

Please contact NotifyIslands' author.
