### ISSUE TITLE
AcidIsland | Parsing Block Mapping | Schematics Issue

### ISSUE THREAD

**Issue by xXSKILLS2015Xx** [tastybento/ASkyBlock-Bugs-N-Features#428]
I changed the settings of the default island in the config.yml to:

    default:
      # Icon - if this is missing or wrong, it will be a MAP
      icon: SAND
      # Order of preference in listing
      order: 1
      # Short name - color codes with & okay
      name: "The Original Island"
      # Longer description. Use | for new lines. Color codes okay.
      description: "&eUsually this is a|&egood start for new|&epeople that want to|&eplay Islands!"
      # Filename of the schematic in the schematic folder
      # Default island does not need a filename
       filename: default.schematic <- This is the custom schematic I made from world edit and put into the AcidIsland schematics folder
      # Use default chest if true, or use schematic chest contents if false
      useDefaultChest: true
      partnerSchematic: nether
      #Level handicap zeros the initial island level. Will not retroactively change islands already created. 
      levelHandicap: 2

I get this error about mapping in my console on start:
`> [04:13:58 INFO]: [AcidIsland] Enabling AcidIsland v3.0.7
> [04:13:58 ERROR]: Cannot load plugins/AcidIsland/config.yml
org.bukkit.configuration.InvalidConfigurationException: while parsing a block mapping
in 'string', line 939, column 7:
icon: SAND
expected <block end>, but found BlockMappingStart
in 'string', line 948, column 8:
filename: default.schematic
at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:57) ~[server.jar:git-Spigot-21fe707-e1ebe52]
at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:226) ~[server.jar:git-Spigot-21fe707-e1ebe52]
at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:169) ~[server.jar:git-Spigot-21fe707-e1ebe52]
at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:180) [server.jar:git-Spigot-21fe707-e1ebe52]
at org.bukkit.plugin.java.JavaPlugin.reloadConfig(JavaPlugin.java:188) [server.jar:git-Spigot-21fe707-e1ebe52]
at org.bukkit.plugin.java.JavaPlugin.getConfig(JavaPlugin.java:162) [server.jar:git-Spigot-21fe707-e1ebe52]
at com.wasteofplastic.acidisland.ASkyBlock.onEnable(ASkyBlock.java:269) [acidisland.jar:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) [server.jar:git-Spigot-21fe707-e1ebe52]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [server.jar:git-Spigot-21fe707-e1ebe52]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [server.jar:git-Spigot-21fe707-e1ebe52]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [server.jar:git-Spigot-21fe707-e1ebe52]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [server.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:199) [server.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [server.jar:git-Spigot-21fe707-e1ebe52]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: org.yaml.snakeyaml.parser.ParserException: while parsing a block mapping
in 'string', line 939, column 7:
icon: SAND
expected <block end>, but found BlockMappingStart
in 'string', line 948, column 8:
filename: default.schematic
at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:570) ~[server.jar:git-Spigot-21fe707-e1ebe52]
at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158) ~[server.jar:git-Spigot-21fe707-e1ebe52]
at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:143) ~[server.jar:git-Spigot-21fe707-e1ebe52]
at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:224) ~[server.jar:git-Spigot-21fe707-e1ebe52]
at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155) ~[server.jar:git-Spigot-21fe707-e1ebe52]
at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:229) ~[server.jar:git-Spigot-21fe707-e1ebe52]
at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155) ~[server.jar:git-Spigot-21fe707-e1ebe52]
at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:229) ~[server.jar:git-Spigot-21fe707-e1ebe52]
at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155) ~[server.jar:git-Spigot-21fe707-e1ebe52]
at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:229) ~[server.jar:git-Spigot-21fe707-e1ebe52]
at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155) ~[server.jar:git-Spigot-21fe707-e1ebe52]
at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:122) ~[server.jar:git-Spigot-21fe707-e1ebe52]
at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:105) ~[server.jar:git-Spigot-21fe707-e1ebe52]
at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:120) ~[server.jar:git-Spigot-21fe707-e1ebe52]
at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:450) ~[server.jar:git-Spigot-21fe707-e1ebe52]
at org.yaml.snakeyaml.Yaml.load(Yaml.java:369) ~[server.jar:git-Spigot-21fe707-e1ebe52]
at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:55) ~[server.jar:git-Spigot-21fe707-e1ebe52]
... 14 more
> [04:13:58 ERROR]: [AcidIsland] +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
> [04:13:58 ERROR]: [AcidIsland] More set up is required. Go to config.yml and edit it.
> [04:13:58 ERROR]: [AcidIsland]
> [04:13:58 ERROR]: [AcidIsland] Make sure you set island distance. If upgrading, set it to what it was before.
> [04:13:58 ERROR]: [AcidIsland]
> [04:13:58 ERROR]: [AcidIsland] +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+`

I have kept messing around with the settings and keep comparing to the default config.yml but nothing has worked for me so far yet.

**Comment by tastybento** [comment]
Your YAML is incorrect - you have a space before the word "filename:".

**Comment by xXSKILLS2015Xx** [comment]
Thank you, I can say that I have no further issues and that this has been solved.
