### ISSUE TITLE
AcidIsland & ASkyBlock problem

### ISSUE THREAD

**Issue by montlikadani** [tastybento/ASkyBlock-Bugs-N-Features#431]
When I start the server, the plugin loads and translates the language into Hungarian (which I did) and did not generate the specified file. You only allow me to extract the file from WinRar. **Specifies this error:**
`[18:07:10] [Server thread/ERROR]: [AcidIsland] 'hu-HU.yml' not found in /locale folder. Using /locale/en-US.yml`
**Plus, you make this error at the server startup:**
```
[18:07:11] [Server thread/ERROR]: Could not pass event ChunkLoadEvent to AcidIsland v3.0.7
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.ChunkProviderServer.originalGetChunkAt(ChunkProviderServer.java:168) [spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:118) [spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:97) [spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.ChunkProviderServer.getOrCreateChunk(ChunkProviderServer.java:197) [spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.World.getChunkAt(World.java:355) [spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.World.getChunkAtWorldCoords(World.java:351) [spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.World.getType(World.java:784) [spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.World.getType(World.java:765) [spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.World.isEmpty(World.java:290) [spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.World.c(World.java:278) [spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.WorldProvider.canSpawn(SourceFile:79) [spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.WorldServer.canSpawn(WorldServer.java:201) [spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.WorldServer.b(WorldServer.java:879) [spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.WorldServer.a(WorldServer.java:801) [spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:273) [spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-21fe707-e1ebe52]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(Unknown Source) ~[?:1.8.0_121]
	at java.util.ArrayList.get(Unknown Source) ~[?:1.8.0_121]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.getDefaultGameMode(CraftServer.java:1419) ~[spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.createWorld(CraftServer.java:883) ~[spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.Bukkit.createWorld(Bukkit.java:464) ~[spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.WorldCreator.createWorld(WorldCreator.java:261) ~[spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-21fe707-e1ebe52]
	at com.wasteofplastic.acidisland.ASkyBlock.getIslandWorld(ASkyBlock.java:154) ~[?:?]
	at com.wasteofplastic.acidisland.listeners.WorldLoader.onChunkLoad(WorldLoader.java:53) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_121]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-21fe707-e1ebe52]
	... 21 more
[18:07:11] [Server thread/INFO]: Preparing start region for level 0 (Seed: 8938511652480558212)
```
Config.yml: https://pastebin.com/xBM04VZJ

**Comment by tastybento** [comment]
Delete, or move the locale folder. Then reload/restart. The language files we be generated.

For the error you see, I don't know why that is happening. Try a complete reset of the world and plugin. (Delete the world folders).

**Comment by montlikadani** [comment]
I've done these things since I started, but I still do the same thing.

**Comment by tastybento** [comment]
I just tested on 1.8.8 with a new install and it works great. I'm sorry, I don't know how to help any more.

**Comment by montlikadani** [comment]
Thank you for your help.
