### ISSUE TITLE
Challenges with requiredItems: monster_egg

### ISSUE THREAD

**Issue by Vyvhen** [tastybento/ASkyBlock-Bugs-N-Features#433]
Today upgrading from serverversion 1.8.x to 1.12.
I'm unable to create a challenge that requires a MONSTER_EGG.

in 1.8.x MONSTER_EGG:90:1 worked fine, but now it doesn't:
Only says 'You do not hace enough required item(s)' ingame, no error in consol.

Trying MONSTER_EGG:PIG:1, as in rewards (there it works):
Nothing ingame, but thie error in consol:

```
[Server thread/ERROR]: Could not pass event InventoryClickEvent to ASkyBlock v3.0.7
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[craftbukkit.jar:git-Spigot-596221b-2c5c611]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit.jar:git-Spigot-596221b-2c5c611]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [craftbukkit.jar:git-Spigot-596221b-2c5c611]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [craftbukkit.jar:git-Spigot-596221b-2c5c611]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1877) [craftbukkit.jar:git-Spigot-596221b-2c5c611]
	at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:33) [craftbukkit.jar:git-Spigot-596221b-2c5c611]
	at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:10) [craftbukkit.jar:git-Spigot-596221b-2c5c611]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [craftbukkit.jar:git-Spigot-596221b-2c5c611]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_101]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_101]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [craftbukkit.jar:git-Spigot-596221b-2c5c611]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:747) [craftbukkit.jar:git-Spigot-596221b-2c5c611]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [craftbukkit.jar:git-Spigot-596221b-2c5c611]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [craftbukkit.jar:git-Spigot-596221b-2c5c611]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [craftbukkit.jar:git-Spigot-596221b-2c5c611]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: org.bukkit.command.CommandException: Unhandled exception executing command 'asc' in plugin ASkyBlock v3.0.7
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[craftbukkit.jar:git-Spigot-596221b-2c5c611]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[craftbukkit.jar:git-Spigot-596221b-2c5c611]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:641) ~[craftbukkit.jar:git-Spigot-596221b-2c5c611]
	at org.bukkit.craftbukkit.v1_12_R1.entity.CraftPlayer.performCommand(CraftPlayer.java:246) ~[craftbukkit.jar:git-Spigot-596221b-2c5c611]
	at com.wasteofplastic.askyblock.panels.ControlPanel.onInventoryClick(ControlPanel.java:299) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor167.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_101]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_101]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[craftbukkit.jar:git-Spigot-596221b-2c5c611]
	... 15 more
Caused by: java.lang.NumberFormatException: For input string: "PIG"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:1.8.0_101]
	at java.lang.Integer.parseInt(Integer.java:580) ~[?:1.8.0_101]
	at java.lang.Integer.parseInt(Integer.java:615) ~[?:1.8.0_101]
	at com.wasteofplastic.askyblock.commands.Challenges.hasRequired(Challenges.java:1117) ~[?:?]
	at com.wasteofplastic.askyblock.commands.Challenges.checkIfCanCompleteChallenge(Challenges.java:840) ~[?:?]
	at com.wasteofplastic.askyblock.commands.Challenges.onCommand(Challenges.java:207) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[craftbukkit.jar:git-Spigot-596221b-2c5c611]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[craftbukkit.jar:git-Spigot-596221b-2c5c611]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:641) ~[craftbukkit.jar:git-Spigot-596221b-2c5c611]
	at org.bukkit.craftbukkit.v1_12_R1.entity.CraftPlayer.performCommand(CraftPlayer.java:246) ~[craftbukkit.jar:git-Spigot-596221b-2c5c611]
	at com.wasteofplastic.askyblock.panels.ControlPanel.onInventoryClick(ControlPanel.java:299) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor167.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_101]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_101]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[craftbukkit.jar:git-Spigot-596221b-2c5c611]
	... 15 more
```
Did I missed something

**Comment by tastybento** [comment]
Yes. Mojang changed how monster eggs are defined big time from numbers to meta data in newer servers. That is why the :90 doesn't work anymore. Unfortunately, it is not possible in the current plugin to identify monster egg types as a required item. So, this is kind of a bug. I'll need to investigate the effort required to add this.

**Comment by Poslovitch** [comment]
What about this one @tastybento ? Will we drop support for mob spawners and egg spawners, or consider it as bug that must be fixed?

**Comment by tastybento** [comment]
Eggs work. It'll take some coding to make spawners work. I can maybe try and get it working this week.
