### ISSUE TITLE
Errors in Log

### ISSUE THREAD

**Issue by TheDGOfficial** [tastybento/ASkyBlock-Bugs-N-Features#465]
İ see this errors in log.

`[06:42:24] [Craft Scheduler Thread - 171/WARN]: Exception in thread "Craft Scheduler Thread - 171" 
[06:42:24] [Craft Scheduler Thread - 171/WARN]: org.apache.commons.lang.UnhandledException: Plugin ASkyBlock v3.0.3.2 generated an exception while executing task 5
	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
	at java.util.ArrayList$Itr.next(Unknown Source)
	at org.bukkit.craftbukkit.v1_7_R4.CraftWorld.getPlayers(CraftWorld.java:693)
	at com.wasteofplastic.askyblock.Metrics.getOnlinePlayers(Metrics.java:198)
	at com.wasteofplastic.askyblock.Metrics.postPlugin(Metrics.java:139)
	at com.wasteofplastic.askyblock.Metrics.access$200(Metrics.java:29)
	at com.wasteofplastic.askyblock.Metrics$1.run(Metrics.java:226)
	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71)
	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 3 more`

İ not use latest version, i use PaperSpigot 1.7.10.
You can help me? which version is latest for Paper 1.7.10?

**Comment by tastybento** [comment]
You should be using the latest version of the plugin always - 3.0.7.
The issue is caused by an old Metrics code that doesn't work anymore because the metrics service closed. Please update.
