### ISSUE TITLE
An internal error occured while ...

### ISSUE THREAD

**Issue by MRS7777777** [tastybento/ASkyBlock-Bugs-N-Features#475]
Good afternoon everybody,

I just tried to update from 3.0.5.X to the latest version, but it did not work as it is supposed to. After several trys I deleted my whole old ASkyBlock folder (don't worry, I took a backup in advance) and restarted the server again, so that a fully new folder of ASkyBlock is gettin' created. But the plugin is still not working.

> [19:45:06] [Server thread/INFO]: [ASkyBlock] Enabling ASkyBlock v3.0.7
[19:45:07] [Server thread/INFO]: [ASkyBlock] HOPPER will be limited to 30
[19:45:07] [Server thread/INFO]: [ASkyBlock] No blockvalues.yml found. Creating it...
[19:45:07] [Server thread/INFO]: [ASkyBlock] Using default found in jar file.
[19:45:07] [Server thread/WARN]: [ASkyBlock] Unknown material (BEETROOT_BLOCK) in blockvalues.yml blocks section. Skipping...
[19:45:07] [Server thread/WARN]: [ASkyBlock] Unknown material (BLACK_GLAZED_TERRACOTTA) in blockvalues.yml blocks section. Skipping...
[19:45:07] [Server thread/WARN]: [ASkyBlock] Unknown material (BLACK_SHULKER_BOX) in blockvalues.yml blocks section. Skipping...
[19:45:07] [Server thread/WARN]: [ASkyBlock] Unknown material (BLUE_GLAZED_TERRACOTTA) in blockvalues.yml blocks section. Skipping...
[19:45:07] [Server thread/WARN]: [ASkyBlock] Unknown material (BLUE_SHULKER_BOX) in blockvalues.yml blocks section. Skipping...
[19:45:07] [Server thread/WARN]: [ASkyBlock] Unknown material (BOAT_ACACIA) in blockvalues.yml blocks section. Skipping...
[19:45:07] [Server thread/WARN]: [ASkyBlock] Unknown material (BOAT_BIRCH) in blockvalues.yml blocks section. Skipping...
[19:45:07] [Server thread/WARN]: [ASkyBlock] Unknown material (BOAT_DARK_OAK) in blockvalues.yml blocks section. Skipping...
[19:45:07] [Server thread/WARN]: [ASkyBlock] Unknown material (BOAT_JUNGLE) in blockvalues.yml blocks section. Skipping...
[19:45:07] [Server thread/WARN]: [ASkyBlock] Unknown material (BOAT_SPRUCE) in blockvalues.yml blocks section. Skipping...
[19:45:07] [Server thread/WARN]: [ASkyBlock] Unknown material (BONE_BLOCK) in blockvalues.yml blocks section. Skipping...
[19:45:07] [Server thread/WARN]: [ASkyBlock] Unknown material (BROWN_GLAZED_TERRACOTTA) in blockvalues.yml blocks section. Skipping...
[19:45:07] [Server thread/WARN]: [ASkyBlock] Unknown material (BROWN_SHULKER_BOX) in blockvalues.yml blocks section. Skipping...
[19:45:07] [Server thread/WARN]: [ASkyBlock] Unknown material (CHORUS_FLOWER) in blockvalues.yml blocks section. Skipping...
[19:45:07] [Server thread/WARN]: [ASkyBlock] Unknown material (CHORUS_PLANT) in blockvalues.yml blocks section. Skipping...
[19:45:07] [Server thread/WARN]: [ASkyBlock] Unknown material (CONCRETE) in blockvalues.yml blocks section. Skipping...
[19:45:07] [Server thread/WARN]: [ASkyBlock] Unknown material (CONCRETE_POWDER) in blockvalues.yml blocks section. Skipping...
[19:45:07] [Server thread/WARN]: [ASkyBlock] Unknown material (CYAN_GLAZED_TERRACOTTA) in blockvalues.yml blocks section. Skipping...
[19:45:07] [Server thread/WARN]: [ASkyBlock] Unknown material (CYAN_SHULKER_BOX) in blockvalues.yml blocks section. Skipping...
[19:45:07] [Server thread/WARN]: [ASkyBlock] Unknown material (END_BRICKS) in blockvalues.yml blocks section. Skipping...
[19:45:07] [Server thread/WARN]: [ASkyBlock] Unknown material (FROSTED_ICE) in blockvalues.yml blocks section. Skipping...
[19:45:07] [Server thread/WARN]: [ASkyBlock] Unknown material (GRASS_PATH) in blockvalues.yml blocks section. Skipping...
[19:45:07] [Server thread/WARN]: [ASkyBlock] Unknown material (GRAY_GLAZED_TERRACOTTA) in blockvalues.yml blocks section. Skipping...
[19:45:07] [Server thread/WARN]: [ASkyBlock] Unknown material (GRAY_SHULKER_BOX) in blockvalues.yml blocks section. Skipping...
[19:45:07] [Server thread/WARN]: [ASkyBlock] Unknown material (GREEN_GLAZED_TERRACOTTA) in blockvalues.yml blocks section. Skipping...
[19:45:07] [Server thread/WARN]: [ASkyBlock] Unknown material (GREEN_SHULKER_BOX) in blockvalues.yml blocks section. Skipping...
[19:45:07] [Server thread/WARN]: [ASkyBlock] Unknown material (LIGHT_BLUE_GLAZED_TERRACOTTA) in blockvalues.yml blocks section. Skipping...
[19:45:07] [Server thread/WARN]: [ASkyBlock] Unknown material (LIGHT_BLUE_SHULKER_BOX) in blockvalues.yml blocks section. Skipping...
[19:45:07] [Server thread/WARN]: [ASkyBlock] Unknown material (LIME_GLAZED_TERRACOTTA) in blockvalues.yml blocks section. Skipping...
[19:45:07] [Server thread/WARN]: [ASkyBlock] Unknown material (LIME_SHULKER_BOX) in blockvalues.yml blocks section. Skipping...
[19:45:07] [Server thread/WARN]: [ASkyBlock] Unknown material (MAGENTA_GLAZED_TERRACOTTA) in blockvalues.yml blocks section. Skipping...
[19:45:07] [Server thread/WARN]: [ASkyBlock] Unknown material (MAGENTA_SHULKER_BOX) in blockvalues.yml blocks section. Skipping...
[19:45:07] [Server thread/WARN]: [ASkyBlock] Unknown material (MAGMA) in blockvalues.yml blocks section. Skipping...
[19:45:07] [Server thread/WARN]: [ASkyBlock] Unknown material (NETHER_WART_BLOCK) in blockvalues.yml blocks section. Skipping...
[19:45:07] [Server thread/WARN]: [ASkyBlock] Unknown material (OBSERVER) in blockvalues.yml blocks section. Skipping...
[19:45:07] [Server thread/WARN]: [ASkyBlock] Unknown material (ORANGE_GLAZED_TERRACOTTA) in blockvalues.yml blocks section. Skipping...
[19:45:07] [Server thread/WARN]: [ASkyBlock] Unknown material (ORANGE_SHULKER_BOX) in blockvalues.yml blocks section. Skipping...
[19:45:07] [Server thread/WARN]: [ASkyBlock] Unknown material (PINK_GLAZED_TERRACOTTA) in blockvalues.yml blocks section. Skipping...
[19:45:07] [Server thread/WARN]: [ASkyBlock] Unknown material (PINK_SHULKER_BOX) in blockvalues.yml blocks section. Skipping...
[19:45:07] [Server thread/WARN]: [ASkyBlock] Unknown material (PURPLE_GLAZED_TERRACOTTA) in blockvalues.yml blocks section. Skipping...
[19:45:07] [Server thread/WARN]: [ASkyBlock] Unknown material (PURPLE_SHULKER_BOX) in blockvalues.yml blocks section. Skipping...
[19:45:07] [Server thread/WARN]: [ASkyBlock] Unknown material (PURPUR_BLOCK) in blockvalues.yml blocks section. Skipping...
[19:45:07] [Server thread/WARN]: [ASkyBlock] Unknown material (PURPUR_DOUBLE_SLAB) in blockvalues.yml blocks section. Skipping...
[19:45:07] [Server thread/WARN]: [ASkyBlock] Unknown material (PURPUR_PILLAR) in blockvalues.yml blocks section. Skipping...
[19:45:07] [Server thread/WARN]: [ASkyBlock] Unknown material (PURPUR_SLAB) in blockvalues.yml blocks section. Skipping...
[19:45:07] [Server thread/WARN]: [ASkyBlock] Unknown material (PURPUR_STAIRS) in blockvalues.yml blocks section. Skipping...
[19:45:07] [Server thread/WARN]: [ASkyBlock] Unknown material (RED_GLAZED_TERRACOTTA) in blockvalues.yml blocks section. Skipping...
[19:45:07] [Server thread/WARN]: [ASkyBlock] Unknown material (RED_NETHER_BRICK) in blockvalues.yml blocks section. Skipping...
[19:45:07] [Server thread/WARN]: [ASkyBlock] Unknown material (RED_SHULKER_BOX) in blockvalues.yml blocks section. Skipping...
[19:45:07] [Server thread/WARN]: [ASkyBlock] Unknown material (SILVER_GLAZED_TERRACOTTA) in blockvalues.yml blocks section. Skipping...
[19:45:07] [Server thread/WARN]: [ASkyBlock] Unknown material (SILVER_SHULKER_BOX) in blockvalues.yml blocks section. Skipping...
[19:45:07] [Server thread/WARN]: [ASkyBlock] Unknown material (WHITE_GLAZED_TERRACOTTA) in blockvalues.yml blocks section. Skipping...
[19:45:07] [Server thread/WARN]: [ASkyBlock] Unknown material (WHITE_SHULKER_BOX) in blockvalues.yml blocks section. Skipping...
[19:45:07] [Server thread/WARN]: [ASkyBlock] Unknown material (YELLOW_GLAZED_TERRACOTTA) in blockvalues.yml blocks section. Skipping...
[19:45:07] [Server thread/WARN]: [ASkyBlock] Unknown material (YELLOW_SHULKER_BOX) in blockvalues.yml blocks section. Skipping...
[19:45:07] [Server thread/INFO]: [ASkyBlock] No resettimers.yml found. Creating it...
[19:45:07] [Server thread/INFO]: [ASkyBlock] Default schematic does not exist, saving it...
[19:45:07] [Server thread/INFO]: [ASkyBlock] Loaded default nether schematic
[19:45:07] [Server thread/WARN]: Spawner setting of WITHER_SKELETON is unknown for this server. Skipping.
[19:45:07] [Server thread/INFO]: [ASkyBlock] Loaded default nether schematic.
[19:45:07] [Server thread/INFO]: [ASkyBlock] Loading schematic The Original (island.schematic) for all players, order 1
[19:45:07] [Server thread/WARN]: Spawner setting of WITHER_SKELETON is unknown for this server. Skipping.
[19:45:07] [Server thread/INFO]: [ASkyBlock] Loading schematic NetherBlock Island (nether.schematic) for all players, order 0
[19:45:07] [Server thread/INFO]: [ASkyBlock] Loading schematic Island Duo (double.schematic) for all players, order 2
[19:45:07] [Server thread/INFO]: [ASkyBlock] Loading schematic §lBlack §bDiamonds (harder.schematic) for all players, order 3
[19:45:07] [Server thread/INFO]: [ASkyBlock] Loading offline messages...
[19:45:07] [Server thread/INFO]: [ASkyBlock] Silencing command feedback for Ops...
[19:45:07] [Server thread/INFO]: Game rule has been updated
[19:45:07] [Server thread/INFO]: [ASkyBlock] If you do not want this, do /gamerule sendCommandFeedback true
[19:45:07] [Server thread/INFO]: [ASkyBlock] Checking for new updates...
[19:45:07] [Server thread/INFO]: [ASkyBlock] No update available.
[19:45:07] [Server thread/INFO]: [ASkyBlock] Loading island grid...
[19:45:07] [Server thread/INFO]: [ASkyBlock] islands.yml does not exist. Creating...
[19:45:07] [Server thread/WARN]: [ASkyBlock] Reading player folder...
[19:45:07] [Server thread/WARN]: [ASkyBlock] Task #364683 for ASkyBlock v3.0.7 generated an exception
java.lang.LinkageError: loader constraint violation: when resolving method "com.wasteofplastic.askyblock.Island.<init>(Lcom/wasteofplastic/askyblock/ASkyBlock;IILjava/util/UUID;)V" the class loader (instance of org/bukkit/plugin/java/PluginClassLoader) of the current class, com/wasteofplastic/askyblock/GridManager, and the class loader (instance of org/bukkit/plugin/java/PluginClassLoader) for the method's defining class, com/wasteofplastic/askyblock/Island, have different Class objects for the type com/wasteofplastic/askyblock/ASkyBlock used in the signature
	at com.wasteofplastic.askyblock.GridManager.addIsland(GridManager.java:652) ~[?:?]
	at com.wasteofplastic.askyblock.GridManager.convert(GridManager.java:300) ~[?:?]
	at com.wasteofplastic.askyblock.GridManager.loadGrid(GridManager.java:108) ~[?:?]
	at com.wasteofplastic.askyblock.GridManager.<init>(GridManager.java:83) ~[?:?]
	at com.wasteofplastic.askyblock.ASkyBlock$1$1.run(ASkyBlock.java:418) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[server.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [server.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [server.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [server.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [server.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [server.jar:git-Spigot-21fe707-e1ebe52]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
[19:45:13] [Server thread/INFO]: MRS777 issued server command: /is
[19:45:13] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'is' in plugin ASkyBlock v3.0.7
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[server.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[server.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[server.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [server.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [server.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [server.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [server.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [server.jar:git-Spigot-21fe707-e1ebe52]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [server.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [server.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [server.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [server.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [server.jar:git-Spigot-21fe707-e1ebe52]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.NullPointerException
	at com.wasteofplastic.askyblock.commands.IslandCmd.onCommand(IslandCmd.java:1068) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[server.jar:git-Spigot-21fe707-e1ebe52]
	... 15 more

You can also see, that after executing the command '/is' another error appears.

Additional information:
Spigot version: 1.8
ASkyBlock version: 3.0.7

**Comment by tastybento** [comment]
What Java are you using?
Does this happen from a full start, not a reload?
I've never seen this error before.

**Comment by tastybento** [comment]
What is the Java command you are using to run the server? It may be an issue there with the classpath.

**Comment by MRS7777777** [comment]
@tastybento The command is the following one.

java -server -Xms$INITMEM -Xmx$MAXMEM -XX:+UseG1GC -XX:MaxGCPauseMillis=50 -jar spigot.jar

**Comment by MRS7777777** [comment]
And I am running on Java 8 ^^ :)

**Comment by tastybento** [comment]
Okay, nothing odd there. Does this happen every time you start the server?

I've never heard of this error, so I suspect it's a server error. Where did you get your spigot.jar? Did you make it yourself using BuildTools.jar? If so, try and do it again and see if you still see the error.

Also, try this version of the plugin https://github.com/tastybento/askyblock/releases/tag/3.0.7.1c

Finally, do you still see this issue with your older version (with a clean install)?

I might need you to zip up your ASkyBlock folder and drag and drop it to this ticket. If nothing above works, do that and I'll see if I can replicate the issue.

**Comment by MRS7777777** [comment]
Thank you Sir. The latest version you recommended to use, worked fine for me and my server.

**Comment by tastybento** [comment]
Okay, interesting. I'll be releasing it officially this weekend, so there will be a slightly newer version available then.
