### ISSUE TITLE
Could not pass event BlockPistonRetractEvent to ASkyBlock v3.0.7

### ISSUE THREAD

**Issue by TheDGOfficial** [tastybento/ASkyBlock-Bugs-N-Features#498]
Console spam's this error:
`[18:38:11] [Server thread/ERROR]: Could not pass event BlockPistonRetractEvent to ASkyBlock v3.0.7
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:509) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:494) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockPiston.e(BlockPiston.java:82) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockPiston.doPhysics(BlockPiston.java:46) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.e(World.java:694) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.applyPhysics(World.java:644) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.e(BlockRedstoneWire.java:49) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.doPhysics(BlockRedstoneWire.java:237) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.e(World.java:694) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.applyPhysics(World.java:642) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.e(BlockRedstoneWire.java:49) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.doPhysics(BlockRedstoneWire.java:237) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.e(World.java:694) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.applyPhysics(World.java:642) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.e(BlockRedstoneWire.java:49) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.doPhysics(BlockRedstoneWire.java:237) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.e(World.java:694) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.applyPhysics(World.java:643) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.e(BlockRedstoneWire.java:49) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.doPhysics(BlockRedstoneWire.java:237) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.e(World.java:694) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.applyPhysics(World.java:642) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.e(BlockRedstoneWire.java:49) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.doPhysics(BlockRedstoneWire.java:237) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.e(World.java:694) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.applyPhysics(World.java:643) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.e(BlockRedstoneWire.java:49) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.doPhysics(BlockRedstoneWire.java:237) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.e(World.java:694) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.applyPhysics(World.java:642) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.e(BlockRedstoneWire.java:49) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.doPhysics(BlockRedstoneWire.java:237) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.e(World.java:694) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.applyPhysics(World.java:644) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.e(BlockRedstoneWire.java:49) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.doPhysics(BlockRedstoneWire.java:237) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.e(World.java:694) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.applyPhysics(World.java:642) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.e(BlockRedstoneWire.java:49) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.doPhysics(BlockRedstoneWire.java:237) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.e(World.java:694) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.applyPhysics(World.java:644) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.e(BlockRedstoneWire.java:49) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.doPhysics(BlockRedstoneWire.java:237) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.e(World.java:694) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.applyPhysics(World.java:642) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.e(BlockRedstoneWire.java:49) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.doPhysics(BlockRedstoneWire.java:237) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.e(World.java:694) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.applyPhysics(World.java:643) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.e(BlockRedstoneWire.java:49) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.doPhysics(BlockRedstoneWire.java:237) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.e(World.java:694) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.applyPhysics(World.java:642) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.e(BlockRedstoneWire.java:49) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.doPhysics(BlockRedstoneWire.java:237) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.e(World.java:694) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.applyPhysics(World.java:645) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.e(BlockRedstoneWire.java:49) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.doPhysics(BlockRedstoneWire.java:237) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.e(World.java:694) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.applyPhysics(World.java:642) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.e(BlockRedstoneWire.java:49) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.doPhysics(BlockRedstoneWire.java:237) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.e(World.java:694) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.applyPhysics(World.java:646) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.e(BlockRedstoneWire.java:49) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.doPhysics(BlockRedstoneWire.java:237) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.e(World.java:694) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.applyPhysics(World.java:643) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.e(BlockRedstoneWire.java:49) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.doPhysics(BlockRedstoneWire.java:237) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.e(World.java:694) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.applyPhysics(World.java:644) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.e(BlockRedstoneWire.java:49) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.doPhysics(BlockRedstoneWire.java:237) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.e(World.java:694) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.applyPhysics(World.java:642) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.e(BlockRedstoneWire.java:49) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.doPhysics(BlockRedstoneWire.java:237) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.e(World.java:694) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.applyPhysics(World.java:645) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.e(BlockRedstoneWire.java:49) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.doPhysics(BlockRedstoneWire.java:237) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.e(World.java:694) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.applyPhysics(World.java:643) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.e(BlockRedstoneWire.java:49) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.doPhysics(BlockRedstoneWire.java:237) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.e(World.java:694) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.applyPhysics(World.java:643) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.e(BlockRedstoneWire.java:49) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.doPhysics(BlockRedstoneWire.java:237) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.e(World.java:694) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.applyPhysics(World.java:642) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.e(BlockRedstoneWire.java:49) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.doPhysics(BlockRedstoneWire.java:237) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.e(World.java:694) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.applyPhysics(World.java:644) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.e(BlockRedstoneWire.java:49) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.doPhysics(BlockRedstoneWire.java:237) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.e(World.java:694) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.applyPhysics(World.java:643) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.e(BlockRedstoneWire.java:49) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.doPhysics(BlockRedstoneWire.java:237) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.e(World.java:694) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.applyPhysics(World.java:644) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.e(BlockRedstoneWire.java:49) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.doPhysics(BlockRedstoneWire.java:237) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.e(World.java:694) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.applyPhysics(World.java:642) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.e(BlockRedstoneWire.java:49) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.doPhysics(BlockRedstoneWire.java:237) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.e(World.java:694) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.applyPhysics(World.java:643) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.e(BlockRedstoneWire.java:49) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.doPhysics(BlockRedstoneWire.java:237) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.e(World.java:694) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.applyPhysics(World.java:643) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.e(BlockRedstoneWire.java:49) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.doPhysics(BlockRedstoneWire.java:237) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.e(World.java:694) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.applyPhysics(World.java:644) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.e(BlockRedstoneWire.java:49) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.doPhysics(BlockRedstoneWire.java:237) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.e(World.java:694) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.applyPhysics(World.java:642) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.e(BlockRedstoneWire.java:49) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.doPhysics(BlockRedstoneWire.java:237) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.e(World.java:694) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.applyPhysics(World.java:644) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.e(BlockRedstoneWire.java:49) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.doPhysics(BlockRedstoneWire.java:237) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.e(World.java:694) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.applyPhysics(World.java:643) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.e(BlockRedstoneWire.java:49) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.doPhysics(BlockRedstoneWire.java:237) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.e(World.java:694) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.applyPhysics(World.java:643) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.e(BlockRedstoneWire.java:49) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.doPhysics(BlockRedstoneWire.java:237) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.e(World.java:694) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.applyPhysics(World.java:642) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.e(BlockRedstoneWire.java:49) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.doPhysics(BlockRedstoneWire.java:237) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.e(World.java:694) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.applyPhysics(World.java:644) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.e(BlockRedstoneWire.java:49) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.doPhysics(BlockRedstoneWire.java:237) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.e(World.java:694) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.applyPhysics(World.java:643) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.e(BlockRedstoneWire.java:49) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.doPhysics(BlockRedstoneWire.java:237) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.e(World.java:694) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.applyPhysics(World.java:643) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.e(BlockRedstoneWire.java:49) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.doPhysics(BlockRedstoneWire.java:237) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.e(World.java:694) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.applyPhysics(World.java:642) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.e(BlockRedstoneWire.java:49) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.doPhysics(BlockRedstoneWire.java:237) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.e(World.java:694) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.applyPhysics(World.java:643) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.e(BlockRedstoneWire.java:49) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.doPhysics(BlockRedstoneWire.java:237) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.e(World.java:694) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.applyPhysics(World.java:643) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.e(BlockRedstoneWire.java:49) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.doPhysics(BlockRedstoneWire.java:237) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.e(World.java:694) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.applyPhysics(World.java:643) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.e(BlockRedstoneWire.java:49) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.doPhysics(BlockRedstoneWire.java:237) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.e(World.java:694) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.applyPhysics(World.java:642) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.e(BlockRedstoneWire.java:49) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.doPhysics(BlockRedstoneWire.java:237) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.e(World.java:694) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.applyPhysics(World.java:642) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.e(BlockRedstoneWire.java:49) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.doPhysics(BlockRedstoneWire.java:237) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.e(World.java:694) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.applyPhysics(World.java:642) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.e(BlockRedstoneWire.java:49) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.doPhysics(BlockRedstoneWire.java:237) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.e(World.java:694) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.applyPhysics(World.java:643) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.e(BlockRedstoneWire.java:49) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockRedstoneWire.doPhysics(BlockRedstoneWire.java:237) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.e(World.java:694) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.World.applyPhysics(World.java:647) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.BlockLever.interact(BlockLever.java:227) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.PlayerInteractManager.interact(PlayerInteractManager.java:391) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:666) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:50) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.PacketPlayInBlockPlace.handle(PacketPlayInBlockPlace.java:86) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:189) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:795) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:307) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:643) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:549) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
Caused by: java.lang.NoSuchMethodError: org.bukkit.event.block.BlockPistonRetractEvent.getBlocks()Ljava/util/List;
	at com.wasteofplastic.askyblock.listeners.IslandGuard.onEvent(IslandGuard.java:2477) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_144]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_144]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_144]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_144]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:298) ~[PaperSpigot.jar:git-PaperSpigot-1f7d532]
	... 203 more`

**Comment by tastybento** [comment]
It looks like your server does not support the getBlocks() method because it's old. You can update your server to a newer version, or change general.allowTNTpushing back to true.
