### ISSUE TITLE
NullException

### ISSUE THREAD

**Issue by UnioDex** [tastybento/ASkyBlock-Bugs-N-Features#508]
**Versions:**
TacoSpigot 1.8.8
ASkyBlock 3.0.7

**Description:**
When players restart their islands if is there any "Duplicate or overlapping islands" a NullPointer Exception shows. 

**Logs:**
```
[19:36:44] [Server thread/INFO]: steve9999 issued server command: /island confirm
[19:36:44] [Server thread/INFO]: [ASkyBlock] Found solid block at island height - adding to islands.yml 10560,27940
[19:36:44] [Server thread/WARN]: [ASkyBlock] *** Duplicate or overlapping islands! ***
[19:36:44] [Server thread/WARN]: [ASkyBlock] Island at (10560, 27940) conflicts with (10560, 27940)
[19:36:44] [Server thread/WARN]: [ASkyBlock] Accepted island is unowned.
[19:36:44] [Server thread/WARN]: [ASkyBlock] Denied island is unowned and was just found in the islands folder. Skipping it...
[19:36:44] [Server thread/WARN]: [ASkyBlock] Recommend that the denied player file is deleted otherwise weird things can happen.
[19:36:44] [Server thread/WARN]: [ASkyBlock] Protection range must be even, using 106 for steve9999
[19:36:46] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'island' in plugin ASkyBlock v3.0.7
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[spigot.jar:git-TacoSpigot-"27784328"]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:143) ~[spigot.jar:git-TacoSpigot-"27784328"]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:666) ~[spigot.jar:git-TacoSpigot-"27784328"]
	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1194) [spigot.jar:git-TacoSpigot-"27784328"]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1006) [spigot.jar:git-TacoSpigot-"27784328"]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-TacoSpigot-"27784328"]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-TacoSpigot-"27784328"]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-TacoSpigot-"27784328"]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot.jar:git-TacoSpigot-"27784328"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774) [spigot.jar:git-TacoSpigot-"27784328"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [spigot.jar:git-TacoSpigot-"27784328"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [spigot.jar:git-TacoSpigot-"27784328"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [spigot.jar:git-TacoSpigot-"27784328"]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.NullPointerException
	at com.wasteofplastic.askyblock.CoopPlay.clearAllIslandCoops(CoopPlay.java:345) ~[?:?]
	at com.wasteofplastic.askyblock.commands.IslandCmd.resetPlayer(IslandCmd.java:3170) ~[?:?]
	at com.wasteofplastic.askyblock.commands.IslandCmd.onCommand(IslandCmd.java:1519) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot.jar:git-TacoSpigot-"27784328"]
	... 15 more
```

**Comment by tastybento** [comment]
Thanks!
