### ISSUE TITLE
ConcurrentModificationException on disable

### ISSUE THREAD

**Issue by Rsl1122** [tastybento/ASkyBlock-Bugs-N-Features#531]
```
[14:42:07 ERROR]: [ASkyBlock] Something went wrong saving files!
[14:42:07 WARN]: java.util.ConcurrentModificationException
[14:42:07 WARN]:        at java.util.HashMap$HashIterator.nextNode(Unknown Source)
[14:42:07 WARN]:        at java.util.HashMap$KeyIterator.next(Unknown Source)
[14:42:07 WARN]:        at com.wasteofplastic.askyblock.PlayerCache.removeAllPlayers(PlayerCache.java:123)
[14:42:07 WARN]:        at com.wasteofplastic.askyblock.ASkyBlock.onDisable(ASkyBlock.java:212)
[14:42:07 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266)
[14:42:07 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:344)
[14:42:07 WARN]:        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:424)
[14:42:07 WARN]:        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:417)
[14:42:07 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.disablePlugins(CraftServer.java:350)
[14:42:07 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.stop(MinecraftServer.java:486)
[14:42:07 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:701)
[14:42:07 WARN]:        at java.lang.Thread.run(Unknown Source)
```

Caused by: Another plugin reading ASkyBlock data through API during ASkyBlock onDisable

**Comment by tastybento** [comment]
If it's caused by another plugin doing that, what can I do here?

**Comment by Rsl1122** [comment]
Up to you, I just reported it since it says "Something went wrong saving files" and thought it might break something (even though it's just clearing a HashMap)

**Comment by tastybento** [comment]
Okay, cheers. I’ll see if there’s anything I can do on this.
