### ISSUE TITLE
java.lang.IllegalArgumentException: Water bottles don't have a level!

### ISSUE THREAD

**Issue by TheDGOfficial** [tastybento/ASkyBlock-Bugs-N-Features#541]
I'm getting this error on the console, i think alchemist challange in the /c is throwing this error.

`[12:30:36] [Server thread/INFO]: jtrogo issued server command: /c
[12:30:38] [Server thread/ERROR]: Could not pass event InventoryClickEvent to ASkyBlock v3.0.3.2
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:509) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:494) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:1482) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.PacketPlayInWindowClick.a(PacketPlayInWindowClick.java:15) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.PacketPlayInWindowClick.handle(PacketPlayInWindowClick.java:65) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:189) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:795) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:307) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:643) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:549) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [PaperSpigot.jar:git-PaperSpigot-1f7d532]
Caused by: org.bukkit.command.CommandException: Unhandled exception executing command 'asc' in plugin ASkyBlock v3.0.3.2
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) ~[PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:765) ~[PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at org.bukkit.craftbukkit.v1_7_R4.entity.CraftPlayer.performCommand(CraftPlayer.java:276) ~[PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at com.wasteofplastic.askyblock.panels.ControlPanel.onInventoryClick(ControlPanel.java:278) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor134.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_144]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_144]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:298) ~[PaperSpigot.jar:git-PaperSpigot-1f7d532]
	... 13 more
Caused by: java.lang.IllegalArgumentException: Water bottles don't have a level!
	at org.apache.commons.lang.Validate.isTrue(Validate.java:136) ~[PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at org.bukkit.potion.Potion.<init>(Potion.java:80) ~[PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at org.bukkit.potion.Potion.fromDamage(Potion.java:395) ~[PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at org.bukkit.potion.Potion.fromItemStack(Potion.java:410) ~[PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at com.wasteofplastic.askyblock.commands.Challenges.hasRequired(Challenges.java:1197) ~[?:?]
	at com.wasteofplastic.askyblock.commands.Challenges.checkIfCanCompleteChallenge(Challenges.java:828) ~[?:?]
	at com.wasteofplastic.askyblock.commands.Challenges.onCommand(Challenges.java:198) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) ~[PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:765) ~[PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at org.bukkit.craftbukkit.v1_7_R4.entity.CraftPlayer.performCommand(CraftPlayer.java:276) ~[PaperSpigot.jar:git-PaperSpigot-1f7d532]
	at com.wasteofplastic.askyblock.panels.ControlPanel.onInventoryClick(ControlPanel.java:278) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor134.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_144]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_144]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:298) ~[PaperSpigot.jar:git-PaperSpigot-1f7d532]
	... 13 more`

**Comment by tastybento** [comment]
Yeah, this looks like an old server problem. I can't really solve it. Looks like you're on 1.7.x or something? Also, you are using 3.0.3.2, that is over a year old not supported, but the main issue is the old server code.
