### ISSUE TITLE
Skyblock plugin can't get player list

### ISSUE THREAD

**Issue by Pdani001** [tastybento/ASkyBlock-Bugs-N-Features#585]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version:**
1.7.10

**Plugin version:**
v3.0.8.2

**Description of issue. What happened?**
This error happens after i start the server:
> [19:50:14] [Server thread/ERROR]: Error occurred while enabling ASkyBlock v3.0.8.2 (Is it up to date?)
java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()Ljava/util/Collection;
at com.wasteofplastic.askyblock.PlayerCache.(PlayerCache.java:49) ~[?:?]
at com.wasteofplastic.askyblock.ASkyBlock.onEnable(ASkyBlock.java:334) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[minecraft_server.jar:git-Spigot-1482]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:324) [minecraft_server.jar:git-Spigot-1482]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [minecraft_server.jar:git-Spigot-1482]
at org.bukkit.craftbukkit.v1_7_R3.CraftServer.loadPlugin(CraftServer.java:465) [minecraft_server.jar:git-Spigot-1482]
at org.bukkit.craftbukkit.v1_7_R3.CraftServer.enablePlugins(CraftServer.java:383) [minecraft_server.jar:git-Spigot-1482]
at net.minecraft.server.v1_7_R3.DedicatedServer.init(DedicatedServer.java:136) [minecraft_server.jar:git-Spigot-1482]
at net.minecraft.server.v1_7_R3.MinecraftServer.run(MinecraftServer.java:457) [minecraft_server.jar:git-Spigot-1482]
at net.minecraft.server.v1_7_R3.ThreadServerApplication.run(SourceFile:628) [minecraft_server.jar:git-Spigot-1482]

**Steps to make this happen**

1. Start the server.

**What do you think should happen?**
Not this error.

**Comment by Poslovitch** [comment]
1.7.10 is a very, very, very, very, very, very, very, very, very, very, very, very, old Minecraft version. So old, that we even dropped official support for it. Versions 3.0.5+ are no longer tested on 1.7.

The only thing we can do for you is recommending you to switch on the official version of MC, which is currently 1.12.2.
