### ISSUE TITLE
bug for 'update'

### ISSUE THREAD

**Issue by ProDash1998** [tastybento/ASkyBlock-Bugs-N-Features#607]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version:**1.12.x

**Plugin version:**lastes

[12:58:58 ERROR]: [ASkyBlock] The updater could not contact dev.bukkit.org for updating.
[12:58:58 ERROR]: [ASkyBlock] If you have not recently modified your configuration and this is the first time you are seeing this message, the site may be experiencing temporary downtime.
[12:58:58 ERROR]: [ASkyBlock] null
java.io.IOException: Server returned HTTP response code: 522 for URL: https://api.curseforge.com/servermods/files?projectIds=85189
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source) ~[?:1.8.0_152]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source) ~[?:1.8.0_152]
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source) ~[?:1.8.0_152]
        at com.wasteofplastic.askyblock.Updater.read(Updater.java:711) [askyblock.jar:?]
        at com.wasteofplastic.askyblock.Updater.runUpdater(Updater.java:786) [askyblock.jar:?]
        at com.wasteofplastic.askyblock.Updater.access$100(Updater.java:43) [askyblock.jar:?]
        at com.wasteofplastic.askyblock.Updater$UpdateRunnable.run(Updater.java:781) [askyblock.jar:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_152]
[12:58:58 INFO]: [ASkyBlock] Could not connect to updating service

**Comment by Poslovitch** [comment]
Don't want to sound impolite, but please read the error log first before sending it here, cause it takes us time even to answer a ticket for a common and unremarkable thing. 

Anyway:
```
[12:58:58 ERROR]: [ASkyBlock] The updater could not contact dev.bukkit.org for updating.
[12:58:58 ERROR]: [ASkyBlock] If you have not recently modified your configuration and this is the first time you are seeing this message, the site may be experiencing temporary downtime.
```

Especially:
```
[12:58:58 ERROR]: [ASkyBlock] If you have not recently modified your configuration and this is the first time you are seeing this message, the site may be experiencing temporary downtime.
```

Not all stacktraces from all the exceptions must be sent to the developers as "bugs". They might not look that good in logs, however they are sometimes minor. Read carefully the messages, that'll in most cases tell you what was wrong.

Please watch out for that, next time :)
