### ISSUE TITLE
Error in console thrown when doing /asadmin delete

### ISSUE THREAD

**Issue by successed** [tastybento/ASkyBlock-Bugs-N-Features#664]
i have askyblock version :
V3.0.8.2
and console problems :

[18:25:57] [Server thread/INFO]: izmirmc issued server command: /asadmin delete osmantr
[18:25:57] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'asadmin' in plugin ASkyBlock v3.0.8.2
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[craftbukkit.jar:git-PaperSpigot-"8b18730"]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:143) ~[craftbukkit.jar:git-PaperSpigot-"8b18730"]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:666) ~[craftbukkit.jar:git-PaperSpigot-"8b18730"]
at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1189) [craftbukkit.jar:git-PaperSpigot-"8b18730"]
at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1001) [craftbukkit.jar:git-PaperSpigot-"8b18730"]
at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [craftbukkit.jar:git-PaperSpigot-"8b18730"]
at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [craftbukkit.jar:git-PaperSpigot-"8b18730"]
at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [craftbukkit.jar:git-PaperSpigot-"8b18730"]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_161]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_161]
at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [craftbukkit.jar:git-PaperSpigot-"8b18730"]
at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774) [craftbukkit.jar:git-PaperSpigot-"8b18730"]
at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [craftbukkit.jar:git-PaperSpigot-"8b18730"]
at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [craftbukkit.jar:git-PaperSpigot-"8b18730"]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [craftbukkit.jar:git-PaperSpigot-"8b18730"]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
Caused by: java.lang.NullPointerException
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[craftbukkit.jar:git-PaperSpigot-"8b18730"]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:666) ~[craftbukkit.jar:git-PaperSpigot-"8b18730"]
at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.performCommand(CraftPlayer.java:339) ~[craftbukkit.jar:git-PaperSpigot-"8b18730"]
at com.wasteofplastic.askyblock.GridManager.removePlayersFromIsland(GridManager.java:1630) ~[?:?]
at com.wasteofplastic.askyblock.ASkyBlock.deletePlayerIsland(ASkyBlock.java:585) ~[?:?]
at com.wasteofplastic.askyblock.commands.AdminCmd.onCommand(AdminCmd.java:1617) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[craftbukkit.jar:git-PaperSpigot-"8b18730"]
... 15 more

**Comment by TNTUP** [comment]
Lol, still on 1.8.x? Try updating Spigot and try? I  don't have such errors on my 1.12.2 server :)

**Comment by Poslovitch** [comment]
Firstly, and before I start reading your issue : this is **useless* to post it on THREE different repositories (as a PR on ASkyBlock, here, and as an issue on BSkyBlock). If you thought it was going to make your issue being solved faster, then I'd suggest you [to read that](https://github.com/tastybento/ASkyBlock-Bugs-N-Features#warning).

Then, your issue does not fit [these requirements](https://github.com/tastybento/ASkyBlock-Bugs-N-Features#bug-reports) and is not using [our template](https://github.com/tastybento/ASkyBlock-Bugs-N-Features/blob/master/ISSUE_TEMPLATE.md).

Finally, `/placetopten` is not a command from ASkyBlock but rather from TopTenHeads, nor is "help us" a good title for an issue.

Now, I'll just rename the issue and wait for you to add the information we need such as the detailed /version and the steps you did to make such an exception appear.

**Comment by successed** [comment]
serverversion git-PaperSpigot-"8b18730" (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
when the player is in the game, i use /asadmin delete <player> check this console log.
if player is online : http://prntscr.com/im6lrn
else player offline : http://prntscr.com/im6m7z
[latest.log](https://github.com/tastybento/ASkyBlock-Bugs-N-Features/files/1777178/latest.log)
i using a Proxy (waterfall bungeecord,)
plugin list : http://prntscr.com/im6mr1

**Comment by successed** [comment]
serverversion git-PaperSpigot-"8b18730" (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
when the player is in the game, i use /asadmin delete check this console log.
if player is online : http://prntscr.com/im6lrn
else player offline : http://prntscr.com/im6m7z
latest.log<https://github.com/tastybento/ASkyBlock-Bugs-N-Features/files/1777178/latest.log>
i using a Proxy (waterfall bungeecord,)
plugin list : http://prntscr.com/im6mr1

[https://image.prntscr.com/image/gkhEONrFSOGeh0yyFe6FjQ.png]<http://prntscr.com/im6mr1>

Screenshot<http://prntscr.com/im6mr1>
prntscr.com
Captured with Lightshot





I have to play in this version.


________________________________
Gönderen: Yann <notifications@github.com>
Gönderildi: 2 Mart 2018 Cuma 19:51
Kime: tastybento/ASkyBlock-Bugs-N-Features
Bilgi: successed; Author
Konu: Re: [tastybento/ASkyBlock-Bugs-N-Features] help us (#664)


Lol, still on 1.8.x? Try updating Spigot and try? I don't have such errors on my 1.12.2 server :)

**Comment by tastybento** [comment]
@successed 

> if player is online : http://prntscr.com/im6lrn

This error is caused by the plugin trying to do **/spawn** for the player. I don't know why that would cause an error - it should just fail silently. Do you have a plugin that uses that command?

**Comment by successed** [comment]
i used now essentialsspawn and before use skript spawn..

skript : 
command /setspawn:
    description: SetSpawn
    usage: /setspawn
    permission: skript.spawn
    trigger:
        set {spawn} to location of player
        message "Spawn kaydedildi!"
        stop    
   
on first join:
    teleport player to {spawn}
    stop   

on join:
    teleport player to {spawn}
    stop

on login:
    teleport player to {spawn}
    stop

on respawn:
    teleport player to {spawn}
    stop
   
command /spawn:
    trigger:
        teleport player to {spawn}
        stop

**Comment by tastybento** [comment]
That is the problem then. It just looks like an incompatibility. Not much I can do, sorry.
