### ISSUE TITLE
island reset error

### ISSUE THREAD

**Issue by DailyStruggle** [tastybento/ASkyBlock-Bugs-N-Features#677]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version:**
spigot 1.12.2 (bungee network)

**Plugin version:**
V3.0.8.2

**What other plugins are you using? (do /plugins and paste here)**
AdvancedBan v2.1.4-RELEASE
ASkyBlock v3.0.8.2
AutoRestart v2.11.1
AutoSaveWorld v4.15
BannerMaker v1.8.0
BungeePortals v1.2
BungeeTabListPlus v2.8.1
ChatControl v5.6.4
ClearLag v2.9.7
ColoredAnvils v1.08
ConsoleSpamFix v1.5.0
CoreProtect v2.14.2
CraftBook v3.9-SNAPSHOT-6223a08
CrazyAuctions v1.2.4
CrazyEnchantments v1.7.9.3.7
DecoHeads v1.4
DiscordSRV v16.0
EditableSign v3.3.0
Essentials v2.0.1-b488
GriefPrevention v16.8
Hub v1.5
Jobs v4.5.1
KeepChunks v1.4.2
LockettePro v2.9.0
LuckPerms v4.0.80
MultiWorld v5.2.8
MyCommand v5.3.4
NoPlugins v6.5.2
NoteBlockUI v1.0.4
PhatLoots v4.2.3
PlugMan v2.1.4
ProtocolLib v4.3.0
ServerSigns v4.5.1
ShopGUIPlus v1.9.0
SilkSpawners v5.0.0
SimpleTrading v1.4
SuperVanish v5.10.0
Vault v1.5.6-b49
ViaBackwards v2.3.1
ViaRewind v1.3.3
ViaVersion v1.3.0
VoidGenerator v1.2.0
WorldEdit v6.1.8-SNAPSHOT;cd4729f
WorldGuard v6.2.1;84bc322

**Description of issue. What happened?**
With an island icon defined as a block variant (eg 17:2), after doing /is restart or /is reset, the command /is confirm returns an internal error

console:
```
[16:00:44] [Server thread/INFO]: leaf26 issued server command: /is confirm
[16:00:44] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'is' in plugin ASkyBlock v3.0.8.2
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-3d850ec-809c399]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-3d850ec-809c399]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:649) ~[spigot.jar:git-Spigot-3d850ec-809c399]
	at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1397) [spigot.jar:git-Spigot-3d850ec-809c399]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1232) [spigot.jar:git-Spigot-3d850ec-809c399]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-3d850ec-809c399]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-3d850ec-809c399]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-3d850ec-809c399]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_161]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_161]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot.jar:git-Spigot-3d850ec-809c399]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot.jar:git-Spigot-3d850ec-809c399]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot.jar:git-Spigot-3d850ec-809c399]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot.jar:git-Spigot-3d850ec-809c399]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot.jar:git-Spigot-3d850ec-809c399]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
Caused by: java.lang.NullPointerException
	at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:68) ~[spigot.jar:git-Spigot-3d850ec-809c399]
	at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:46) ~[spigot.jar:git-Spigot-3d850ec-809c399]
	at com.wasteofplastic.askyblock.panels.SPItem.<init>(SPItem.java:77) ~[?:?]
	at com.wasteofplastic.askyblock.panels.SchematicsPanel.getPanel(SchematicsPanel.java:68) ~[?:?]
	at com.wasteofplastic.askyblock.commands.IslandCmd.onCommand(IslandCmd.java:1526) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-3d850ec-809c399]
	... 15 more
```

**Steps to make this happen**
1. define a custom island, using a block variant
2. create island 
3. do /is reset
4. do /is confirm

**What do you think should happen?**
it should abandon the player's island

**Comment by tastybento** [comment]
It appears to be a YAML issue. If you put the values in quotes, then it works:
icon: '17:2'

However, the plugin should not cause an error, so I'll add some error catching code.

Thanks.
