### ISSUE TITLE
NullPointerException with 3.0.8.3l

### ISSUE THREAD

**Issue by UnioDex** [tastybento/ASkyBlock-Bugs-N-Features#691]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version:**
1.8.8

**Plugin version:**
3.0.8.3l

```
[03:49:24 INFO]: [ASkyBlock] Loading player heads (Rate limit is 1 head/s): 600 to go...
[03:49:36 WARN]: [ASkyBlock] Task #2996569 for ASkyBlock v3.0.8.3 generated an exception
java.lang.NullPointerException
        at com.wasteofplastic.askyblock.commands.IslandCmd$7.run(IslandCmd.java:2674) ~[askyblock.jar:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) ~[spigot.jar:git-TacoSpigot-"bf023c7d"]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:349) [spigot.jar:git-TacoSpigot-"bf023c7d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:785) [spigot.jar:git-TacoSpigot-"bf023c7d"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [spigot.jar:git-TacoSpigot-"bf023c7d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:715) [spigot.jar:git-TacoSpigot-"bf023c7d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:618) [spigot.jar:git-TacoSpigot-"bf023c7d"]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
```

**Comment by tastybento** [comment]
Thanks!

https://github.com/tastybento/askyblock/releases/tag/V3.0.8.3n
