### ISSUE TITLE
Console Spam NullPointer

### ISSUE THREAD

**Issue by UnioDex** [tastybento/ASkyBlock-Bugs-N-Features#693]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version:**
1.8.8
**Plugin version:**
3.0.8.3.purge

**Description of issue. What happened?**
I checked my logs and i saw it is too large. 
```
[22:10:04] [Server thread/INFO]: [ASkyBlock] nazo33's island will be deleted because they joined a party.
[22:10:04] [Server thread/INFO]: [ASkyBlock] Island delete: There are 28 chunks that need to be cleared up.
[22:10:04] [Server thread/INFO]: [ASkyBlock] Clean rate is 2 chunks per second. Should take ~14s
[22:10:04] [Server thread/INFO]: [ASkyBlock] Island deleted.
[22:10:05] [Server thread/WARN]: [ASkyBlock] Task #-1957171870 for ASkyBlock v3.0.8.3 generated an exception
java.lang.NullPointerException
	at com.wasteofplastic.askyblock.PlayerCache.getDeaths(PlayerCache.java:871) ~[askyblock.jar:?]
	at com.wasteofplastic.askyblock.LevelCalcByChunk.tidyUp(LevelCalcByChunk.java:223) ~[askyblock.jar:?]
	at com.wasteofplastic.askyblock.LevelCalcByChunk.access$200(LevelCalcByChunk.java:33) ~[askyblock.jar:?]
	at com.wasteofplastic.askyblock.LevelCalcByChunk$1.run(LevelCalcByChunk.java:84) ~[askyblock.jar:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) ~[spigot.jar:git-TacoSpigot-"bf023c7d"]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:349) [spigot.jar:git-TacoSpigot-"bf023c7d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:785) [spigot.jar:git-TacoSpigot-"bf023c7d"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [spigot.jar:git-TacoSpigot-"bf023c7d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:715) [spigot.jar:git-TacoSpigot-"bf023c7d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:618) [spigot.jar:git-TacoSpigot-"bf023c7d"]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
```
The exception is filled my logs until restart. I dont know what it is.

**Steps to make this happen**

1.  I can't reproduce.

**Comment by tastybento** [comment]
This is an interesting edge case. The player was in the middle of having his island level calculated when he joined a team and it was deleted. Good catch. I'll fix it.
