### ISSUE TITLE
ChunkLoadEvent

### ISSUE THREAD

**Issue by IronLeo03** [tastybento/ASkyBlock-Bugs-N-Features#695]
Server version: This server is running CraftBukkit version git-Spigot-db6de12-18fbb24 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

Plugin version: ASkyBlock v3.0.8.2

What other plugins are you using? (do /plugins and paste here): [18:02:29 INFO]: Plugins (8): PermissionsEx, WorldEdit, ViaVersion, Vault, WorldGuard, ASkyBlock, Essentials, EssentialsChat

Description of issue. What happened?:

```
[17:58:54 ERROR]: Could not pass event ChunkLoadEvent to ASkyBlock v3.0.8.2
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.ChunkProviderServer.originalGetChunkAt(ChunkProviderServer.java:168) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:118) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:97) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.ChunkProviderServer.getOrCreateChunk(ChunkProviderServer.java:197) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.World.getChunkAt(World.java:355) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.World.getChunkAtWorldCoords(World.java:351) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.World.getType(World.java:784) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.World.getType(World.java:765) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.World.isEmpty(World.java:290) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.World.c(World.java:278) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.WorldProvider.canSpawn(SourceFile:79) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.WorldServer.canSpawn(WorldServer.java:201) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.WorldServer.b(WorldServer.java:879) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.WorldServer.a(WorldServer.java:801) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:273) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(Unknown Source) ~[?:1.8.0_161]
        at java.util.ArrayList.get(Unknown Source) ~[?:1.8.0_161]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.getDefaultGameMode(CraftServer.java:1419) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.createWorld(CraftServer.java:883) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.Bukkit.createWorld(Bukkit.java:464) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.WorldCreator.createWorld(WorldCreator.java:261) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        at com.wasteofplastic.askyblock.ASkyBlock.getIslandWorld(ASkyBlock.java:156) ~[?:?]
        at com.wasteofplastic.askyblock.listeners.WorldLoader.onChunkLoad(WorldLoader.java:53) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_161]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_161]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_161]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_161]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        ... 21 more
```

**Steps to make this happen**

1.  Start the server
What do you think should happen? i don't know

**Comment by tastybento** [comment]
Do you see this error if you start the server from scratch? Do you see it every time, sometimes or just once?
