### ISSUE TITLE
/is top Exception

### ISSUE THREAD

**Issue by UnioDex** [tastybento/ASkyBlock-Bugs-N-Features#699]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version:**
1.8.8
**Plugin version:**
3.0.8.3 (latest on spigot)

**Steps to make this happen**

1. Use /asadmin topten
2. Use /is top
3. Take the error:
```[01:12:08 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'is' in plugin ASkyBlock v3.0.8.3
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[spigot.jar:git-TacoSpigot-"bf023c7d"]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:143) ~[spigot.jar:git-TacoSpigot-"bf023c7d"]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:666) ~[spigot.jar:git-TacoSpigot-"bf023c7d"]
        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1194) [spigot.jar:git-TacoSpigot-"bf023c7d"]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1006) [spigot.jar:git-TacoSpigot-"bf023c7d"]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-TacoSpigot-"bf023c7d"]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-TacoSpigot-"bf023c7d"]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-TacoSpigot-"bf023c7d"]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot.jar:git-TacoSpigot-"bf023c7d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:776) [spigot.jar:git-TacoSpigot-"bf023c7d"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [spigot.jar:git-TacoSpigot-"bf023c7d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:715) [spigot.jar:git-TacoSpigot-"bf023c7d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:618) [spigot.jar:git-TacoSpigot-"bf023c7d"]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.util.ConcurrentModificationException
        at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:719) ~[?:1.8.0_131]
        at java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:752) ~[?:1.8.0_131]
        at java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:750) ~[?:1.8.0_131]
        at com.wasteofplastic.askyblock.TopTen.topTenShow(TopTen.java:329) ~[askyblock.jar:?]
        at com.wasteofplastic.askyblock.commands.IslandCmd.onCommand(IslandCmd.java:1768) ~[askyblock.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot.jar:git-TacoSpigot-"bf023c7d"]
        ... 15 more
```

**Comment by tastybento** [comment]
I don't think this is a new issue. When you do /asadmin topten it runs an asynch task that builds the top ten from the files. It can take a while depending on how many files you have. 

Can you share your player folder (zipped) so I can test a fix? Thanks!

**Comment by UnioDex** [comment]
I pm'd you from Spigot.

**Comment by Xemorr** [comment]
I also have this issue

**Comment by tastybento** [comment]
See fix: https://github.com/tastybento/askyblock/releases/tag/3.0.8.4b
<img width="634" alt="screen shot 2018-04-03 at 10 55 51 pm" src="https://user-images.githubusercontent.com/4407265/38291089-01ee38fa-3793-11e8-9927-dc6adb4306d8.png">

**Comment by ScuroK** [comment]
#708
