### ISSUE TITLE
Serial Crashes

### ISSUE THREAD

**Issue by Patatone** [tastybento/ASkyBlock-Bugs-N-Features#732]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version? Remember to say if it is Spigot/Bukkit/Paper etc.**
Paper-1391 (MC: 1.12.2)

**Plugin version:**
3.0.8.6

**Is this a new install or upgrade from earlier plugin version? If upgrade, what version did you use before?**
upgrade, i don't remember but not too old

**Description of issue. What happened?**
A lot of crash every day without reasons.
https://hastebin.com/opogeqarog.md

**What do you think should happen?**
[09:45:19] [Paper Watchdog Thread/ERROR]: 		com.wasteofplastic.askyblock.panels.WarpPanel.updatePanel(WarpPanel.java:229)
[09:45:19] [Paper Watchdog Thread/ERROR]: 		com.wasteofplastic.askyblock.WarpSigns.removeWarp(WarpSigns.java:349)
[09:45:19] [Paper Watchdog Thread/ERROR]: 		com.wasteofplastic.askyblock.WarpSigns.onSignBreak(WarpSigns.java:91)

**Comment by Patatone** [comment]
Other crash reports:
https://hastebin.com/uzoquqiwow.md
https://hastebin.com/udesasenun.md
https://hastebin.com/suxosaneco.md
https://hastebin.com/zevunibozu.md
https://hastebin.com/neboqerizu.md
https://hastebin.com/ozenonovih.md
https://hastebin.com/xewigugoqa.md
https://hastebin.com/iqaxunetap.md

**Comment by tastybento** [comment]
It's all to do with downloading heads. For some reason, the requests are still blocking (network request takes too long) so the server exits with the watchdog timer. I'm working on a fix that just removes heads from the warp panel completely.

**Comment by Patatone** [comment]
Seems to work well :)

**Comment by Patatone** [comment]
One error in console:
`[19:48:13 ERROR]: Could not pass event InventoryClickEvent to ASkyBlock v3.0.8.7
org.bukkit.event.EventException: null
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.12.2.jar:git-Paper-1391]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.2.jar:git-Paper-1391]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1391]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:515) ~[patched_1.12.2.jar:git-Paper-1391]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:500) ~[patched_1.12.2.jar:git-Paper-1391]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1981) ~[patched_1.12.2.jar:git-Paper-1391]
        at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:33) ~[patched_1.12.2.jar:git-Paper-1391]
        at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.12.2.jar:git-Paper-1391]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.2.jar:git-Paper-1391]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_161]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_161]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [patched_1.12.2.jar:git-Paper-1391]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843) [patched_1.12.2.jar:git-Paper-1391]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:427) [patched_1.12.2.jar:git-Paper-1391]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.2.jar:git-Paper-1391]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1391]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 10
        at com.wasteofplastic.askyblock.TopTen.getPlayer(TopTen.java:458) ~[?:?]
        at com.wasteofplastic.askyblock.TopTen.onInventoryClick(TopTen.java:442) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor745.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1391]
        ... 16 more
`

**Comment by tastybento** [comment]
I’ll fix it tonight.

**Comment by tastybento** [comment]
https://github.com/tastybento/askyblock/releases/tag/3.0.8.7b
