### ISSUE TITLE
Frost Walker Error

### ISSUE THREAD

**Issue by stefanik11** [tastybento/ASkyBlock-Bugs-N-Features#734]
Hello, i have my minecraft server based on plugin AcidIsland. When player leave island (his island) using boots with enchantment Frost Walker console print error  and wrost walker doesn't stop working. This is error:

[22:42:40 ERROR]: Could not pass event IslandExitEvent to XieSkyTab v1.0
java.lang.NoClassDefFoundError: com/wasteofplastic/askyblock/ASkyBlock
	at pl.xierip.xieskytab.util.IslandUtils.isInPushZone(IslandUtils.java:19) ~[?:?]
	at pl.xierip.xieskytab.acidisland.IslandExitListenerAcid.onEvent(IslandExitListenerAcid.java:27) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor357.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[server.jar:git-Paper-1335]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[server.jar:git-Paper-1335]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-Paper-1335]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:515) ~[server.jar:git-Paper-1335]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:500) ~[server.jar:git-Paper-1335]
	at com.wasteofplastic.acidisland.listeners.IslandGuard.onPlayerMove(IslandGuard.java:503) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor498.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[server.jar:git-Paper-1335]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[server.jar:git-Paper-1335]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-Paper-1335]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:515) ~[server.jar:git-Paper-1335]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:500) ~[server.jar:git-Paper-1335]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:692) ~[server.jar:git-Paper-1335]
	at net.minecraft.server.v1_12_R1.PacketPlayInFlying.a(SourceFile:126) ~[server.jar:git-Paper-1335]
	at net.minecraft.server.v1_12_R1.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:57) ~[server.jar:git-Paper-1335]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[server.jar:git-Paper-1335]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_161]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_161]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [server.jar:git-Paper-1335]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843) [server.jar:git-Paper-1335]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426) [server.jar:git-Paper-1335]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [server.jar:git-Paper-1335]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [server.jar:git-Paper-1335]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]

Please, fix this.

**Comment by Poslovitch** [comment]
`java.lang.NoClassDefFoundError: com/wasteofplastic/askyblock/ASkyBlock`

That's on top of the stacktrace. It appears that somehow ASkyBlock main class cannot be found, which means that the jar is missing from the plugins folder or /reload has been issued.
