### ISSUE TITLE
Default schematic not loading

### ISSUE THREAD

**Issue by YanisDark20041** [tastybento/ASkyBlock-Bugs-N-Features#743]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version? Spigot 1.12.2 (Latest)**

**Plugin version: 3.0.8.6**

**Is this a new install or upgrade from earlier plugin version? New install**

**(Optional) What other plugins are you using now? (do /plugins and paste text from the console log here)** Plugins (61): §askript-npc§f, §aVixio§f, §aPlaceholderAPI§f, §aSurveyPlus§f, §aPlugMan§f, §aCustomRecipes§f, §aArconix§f, §aVoxelSniper§f, §aViaVersion§f, §aViaBackwards§f, §aLightAPI§f, §aCoreProtect§f, §aPlayerRadios§f, §aWorldEdit§f, §aSketchMap§f, §aFastCraft§f, §aBuycraftX§f, §aProtocolLib§f, §aeZProtector§f, §aOldPvP§f, §aWildSkript§f, §aCS-CoreLib§f, §aActionAnnouncer§f, §aVault§f, §aUltraPermissions§f, §aCrazyCrates§f, §aBKCommonLib§f, §aWorldGuard§f, §aASkyBlock§f, §aEpicCraftingsPlus§f, §aWormholes§f, §aGUIPlus§f, §aCrazyEnchantments§f, §aSkript§f, §aEssentials§f, §askDragon§f, §aMMOItems§f, §aSkQuery§f, §aSkStuff§f, §aMultiverse-Core§f, §aCitizens§f, §aKitBattle§f, §aEssentialsKitManager§f, §aKitPreview§f, §aHydra§f, §aEssentialsChat§f, §askUtilities§f, §aBlockParticles§f, §aMoarBows§f, §aHolographicDisplays§f, §aMCJukebox§f, §aErsatz§f, §aCitizensCMD§f, §aSkinsRestorer§f, §askRayFall§f, §aEssentialsGeoIP§f, §aEssentialsSpawn§f, §aWirelessRedstone§f, §aSkellett§f, §aUmbaska§f, §aTuSKe

**Description of issue. What happened?** Well, the custom schematic that i used to replace island.schematic is not working and plugin tries to avoid using it, the plugin uses another schematic instead (like duo of black diamond). If i delete the other schematics, the plugin doesn't work anymore.

**Steps to make this happen**

1. Create a schematic using worldedit
2. Name it "island.schematic" and make it replace the default schematic
3. Use /is

**What do you think should happen?**
The schematic should load normally like any other one

LOGS:
[11:49:58] [Server thread/ERROR]: [ASkyBlock] Could not load default schematic!
[11:49:58] [Server thread/WARN]: java.io.IOException
[11:49:58] [Server thread/WARN]: at com.wasteofplastic.askyblock.schematics.Schematic.<init>(Schematic.java:621)
[11:49:58] [Server thread/WARN]: at com.wasteofplastic.askyblock.commands.IslandCmd.loadSchematics(IslandCmd.java:172)
[11:49:58] [Server thread/WARN]: at com.wasteofplastic.askyblock.commands.IslandCmd.<init>(IslandCmd.java:130)
[11:49:58] [Server thread/WARN]: at com.wasteofplastic.askyblock.ASkyBlock.onEnable(ASkyBlock.java:347)
[11:49:58] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[11:49:58] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
[11:49:58] [Server thread/WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402)
[11:49:58] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:384)
[11:49:58] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:333)
[11:49:58] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:206)
[11:49:58] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545)
[11:49:58] [Server thread/WARN]: at java.lang.Thread.run(Thread.java:748)

**Comment by tastybento** [comment]
It looks like the schematicsection of config.yml is messed up. I recommend you copy and paste the original settings in. Then if you are making your own schematic make sure it has a bedrock block in it. If you do /asadmin reload your be told which schematics are loading or not.
