### ISSUE TITLE
Entity Exception for Witch

### ISSUE THREAD

**Issue by JamieSinn** [tastybento/ASkyBlock-Bugs-N-Features#775]
```
[16:08:02] [Server thread/WARN]: Entity threw exception at ASkyBlock:13185.165520243136,5.0,14984.10940599627
[16:08:02] [Server thread/WARN]: java.lang.ClassCastException: org.bukkit.craftbukkit.v1_12_R1.entity.CraftWitch cannot be cast to org.bukkit.entity.Player
[16:08:02] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.EntityWitch.a(EntityWitch.java:163)
[16:08:02] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PathfinderGoalArrowAttack.e(SourceFile:89)
[16:08:02] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PathfinderGoalSelector.a(SourceFile:129)
[16:08:02] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.EntityInsentient.doTick(EntityInsentient.java:677)
[16:08:02] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.EntityLiving.n(EntityLiving.java:2123)
[16:08:02] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.EntityInsentient.n(EntityInsentient.java:508)
[16:08:02] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.EntityMonster.n(EntityMonster.java:24)
[16:08:02] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.EntityWitch.n(EntityWitch.java:123)
[16:08:02] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.EntityLiving.B_(EntityLiving.java:1976)
[16:08:02] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.EntityInsentient.B_(EntityInsentient.java:247)
[16:08:02] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.EntityMonster.B_(EntityMonster.java:28)
[16:08:02] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.World.entityJoinedWorld(World.java:1771)
[16:08:02] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.World.h(World.java:1741)
[16:08:02] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.World.tickEntities(World.java:1562)
[16:08:02] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.WorldServer.tickEntities(WorldServer.java:678)
[16:08:02] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:914)
[16:08:02] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:427)
[16:08:02] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767)
[16:08:02] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665)
[16:08:02] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[16:08:02] [Server thread/WARN]: Entity threw exception at ASkyBlock:13184.373467584319,5.0,14981.489961434814
[16:08:02] [Server thread/WARN]: java.lang.ClassCastException: org.bukkit.craftbukkit.v1_12_R1.entity.CraftWitch cannot be cast to org.bukkit.entity.Player
[16:08:02] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.EntityWitch.a(EntityWitch.java:163)
[16:08:02] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PathfinderGoalArrowAttack.e(SourceFile:89)
[16:08:02] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PathfinderGoalSelector.a(SourceFile:129)
[16:08:02] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.EntityInsentient.doTick(EntityInsentient.java:677)
[16:08:02] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.EntityLiving.n(EntityLiving.java:2123)
[16:08:02] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.EntityInsentient.n(EntityInsentient.java:508)
[16:08:02] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.EntityMonster.n(EntityMonster.java:24)
[16:08:02] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.EntityWitch.n(EntityWitch.java:123)
[16:08:02] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.EntityLiving.B_(EntityLiving.java:1976)
[16:08:02] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.EntityInsentient.B_(EntityInsentient.java:247)
[16:08:02] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.EntityMonster.B_(EntityMonster.java:28)
[16:08:02] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.World.entityJoinedWorld(World.java:1771)
[16:08:02] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.World.h(World.java:1741)
[16:08:02] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.World.tickEntities(World.java:1562)
[16:08:02] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.WorldServer.tickEntities(WorldServer.java:678)
[16:08:02] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:914)
[16:08:02] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:427)
[16:08:02] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767)
[16:08:02] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665)
[16:08:02] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[16:08:04] [Server thread/INFO]: Festus14 issued server command: /vote
[16:08:05] [Server thread/WARN]: Entity threw exception at ASkyBlock:13189.87986697374,5.0,14983.416773339068
[16:08:05] [Server thread/WARN]: java.lang.ClassCastException: org.bukkit.craftbukkit.v1_12_R1.entity.CraftWitch cannot be cast to org.bukkit.entity.Player
[16:08:05] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.EntityWitch.a(EntityWitch.java:163)
[16:08:05] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PathfinderGoalArrowAttack.e(SourceFile:89)
[16:08:05] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PathfinderGoalSelector.a(SourceFile:129)
[16:08:05] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.EntityInsentient.doTick(EntityInsentient.java:677)
[16:08:05] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.EntityLiving.n(EntityLiving.java:2123)
[16:08:05] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.EntityInsentient.n(EntityInsentient.java:508)
[16:08:05] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.EntityMonster.n(EntityMonster.java:24)
[16:08:05] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.EntityWitch.n(EntityWitch.java:123)
[16:08:05] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.EntityLiving.B_(EntityLiving.java:1976)
[16:08:05] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.EntityInsentient.B_(EntityInsentient.java:247)
[16:08:05] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.EntityMonster.B_(EntityMonster.java:28)
[16:08:05] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.World.entityJoinedWorld(World.java:1771)
[16:08:05] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.World.h(World.java:1741)
[16:08:05] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.World.tickEntities(World.java:1562)
[16:08:05] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.WorldServer.tickEntities(WorldServer.java:678)
[16:08:05] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:914)
[16:08:05] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:427)
[16:08:05] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767)
[16:08:05] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665)
[16:08:05] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)```

**Comment by JamieSinn** [comment]
This was upon completing a challenge that required the 3 witches to be nearby.

**Comment by andrewkm** [comment]
This shows a 15 minute sample with the crazy TPS hang it caused when it happened, perhaps will help you track the issue down:

https://timings.aikar.co/?id=8cab5b2468744dd4b68a23ccce221153

**Comment by JamieSinn** [comment]
The completion is giving a player an item, which shouldn't lag.

Will report to paperspigot, thought you might have done something to cause it from the nearby entities.

**Comment by JamieSinn** [comment]
I'll leave this open in case anyone in paper wants to look, or if you have any solutions.

**Comment by JamieSinn** [comment]
Closed in paper 
https://github.com/PaperMC/Paper/issues/1129
