### ISSUE TITLE
Most of the commands dont work for me

### ISSUE THREAD

**Issue by xlGaM3r** [tastybento/ASkyBlock-Bugs-N-Features#784]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version? Remember to say if it is Spigot/Bukkit/Paper etc.**

KCauldron-1.7.10-1614.201-server.jar

**Plugin version:**

Latest

**(Optional) What other plugins are you using now? (do /plugins and paste text from the console log here)**

Plugins (7): Essentials, Vault, Reloader, EssentialsSpawn, EssentialsChat, ASkyBlock, EssentialsProtect

**Description of issue. What happened?**

An Internal error Occured While attempting to perfom this command

**Steps to make this happen**

```
24.05 04:34:17 [Server] INFO ZGO issued server command: /is top
24.05 04:34:17 [Server] ERROR null
24.05 04:34:17 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'is' in plugin ASkyBlock v3.0.8.8
24.05 04:34:17 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[PluginCommand.class:1.7.10-R0.1-SNAPSHOT]
24.05 04:34:17 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) ~[SimpleCommandMap.class:1.7.10-R0.1-SNAPSHOT]
24.05 04:34:17 [Server] INFO at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:717) ~[CraftServer.class:1.7.10-R0.1-SNAPSHOT]
24.05 04:34:17 [Server] INFO at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1317) [nh.class:?]
24.05 04:34:17 [Server] INFO at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1099) [nh.class:?]
24.05 04:34:17 [Server] INFO at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:38) [ir.class:?]
24.05 04:34:17 [Server] INFO at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:53) [ir.class:?]
24.05 04:34:17 [Server] INFO at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245) [ej.class:?]
24.05 04:34:17 [Server] INFO at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
24.05 04:34:17 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:991) [MinecraftServer.class:?]
24.05 04:34:17 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) [lt.class:?]
24.05 04:34:17 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809) [MinecraftServer.class:?]
24.05 04:34:17 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669) [MinecraftServer.class:?]
24.05 04:34:17 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
24.05 04:34:17 [Server] INFO Caused by: java.lang.NoClassDefFoundError: com/wasteofplastic/askyblock/TopTen
24.05 04:34:17 [Server] INFO at com.wasteofplastic.askyblock.commands.IslandCmd.onCommand(IslandCmd.java:1776) ~[?:?]
24.05 04:34:17 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[PluginCommand.class:1.7.10-R0.1-SNAPSHOT]
24.05 04:34:17 [Server] INFO ... 13 more
```

**What do you think should happen?**

Island top Should display

**Comment by tastybento** [comment]
Sorry, I can't support such an old server like KCaudron 1.7.10.
