### ISSUE TITLE
Cannot create new island

### ISSUE THREAD

**Issue by voodootje0** [tastybento/ASkyBlock-Bugs-N-Features#810]
**Server version:** PaperSpigot 1.8.8
**Plugin version:** 3.0.8.8

It is unpossible to create a new island, this counts for completely new players or when you are resetting your island.

Error when you are trying to create an island
>11.06 22:07:25 [Server] WARN Task #16639 for ASkyBlock v3.0.8.8 generated an exception
11.06 22:07:25 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'island' in plugin ASkyBlock v3.0.8.8
11.06 22:07:25 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[TacoSpigot-Fantasy.jar:git-PaperSpigot-"010c651"]
11.06 22:07:25 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:146) ~[TacoSpigot-Fantasy.jar:git-PaperSpigot-"010c651"]
11.06 22:07:25 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:667) ~[TacoSpigot-Fantasy.jar:git-PaperSpigot-"010c651"]
11.06 22:07:25 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.performCommand(CraftPlayer.java:339) ~[TacoSpigot-Fantasy.jar:git-PaperSpigot-"010c651"]
11.06 22:07:25 [Server] INFO at com.wasteofplastic.askyblock.util.Util$2.run(Util.java:528) ~[?:?]
11.06 22:07:25 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) ~[TacoSpigot-Fantasy.jar:git-PaperSpigot-"010c651"]
11.06 22:07:25 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352) [TacoSpigot-Fantasy.jar:git-PaperSpigot-"010c651"]
11.06 22:07:25 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:783) [TacoSpigot-Fantasy.jar:git-PaperSpigot-"010c651"]
11.06 22:07:25 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:381) [TacoSpigot-Fantasy.jar:git-PaperSpigot-"010c651"]
11.06 22:07:25 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [TacoSpigot-Fantasy.jar:git-PaperSpigot-"010c651"]
11.06 22:07:25 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [TacoSpigot-Fantasy.jar:git-PaperSpigot-"010c651"]
11.06 22:07:25 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
11.06 22:07:25 [Server] INFO Caused by: java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
11.06 22:07:25 [Server] INFO at java.util.ArrayList.rangeCheck(ArrayList.java:657) ~[?:1.8.0_171]
11.06 22:07:25 [Server] INFO at java.util.ArrayList.set(ArrayList.java:448) ~[?:1.8.0_171]
11.06 22:07:25 [Server] INFO at net.minecraft.server.v1_8_R3.RegionFile.<init>(RegionFile.java:66) ~[TacoSpigot-Fantasy.jar:git-PaperSpigot-"010c651"]
11.06 22:07:25 [Server] INFO at net.minecraft.server.v1_8_R3.RegionFileCache.a(RegionFileCache.java:39) ~[TacoSpigot-Fantasy.jar:git-PaperSpigot-"010c651"]
11.06 22:07:25 [Server] INFO at net.minecraft.server.v1_8_R3.ChunkRegionLoader.chunkExists(ChunkRegionLoader.java:39) ~[TacoSpigot-Fantasy.jar:git-PaperSpigot-"010c651"]
11.06 22:07:25 [Server] INFO at net.minecraft.server.v1_8_R3.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:130) ~[TacoSpigot-Fantasy.jar:git-PaperSpigot-"010c651"]
11.06 22:07:25 [Server] INFO at net.minecraft.server.v1_8_R3.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:117) ~[TacoSpigot-Fantasy.jar:git-PaperSpigot-"010c651"]
11.06 22:07:25 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftWorld.getChunkAt(CraftWorld.java:145) ~[TacoSpigot-Fantasy.jar:git-PaperSpigot-"010c651"]
11.06 22:07:25 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftWorld.getBlockAt(CraftWorld.java:91) ~[TacoSpigot-Fantasy.jar:git-PaperSpigot-"010c651"]
11.06 22:07:25 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftWorld.getBlockAt(CraftWorld.java:592) ~[TacoSpigot-Fantasy.jar:git-PaperSpigot-"010c651"]
11.06 22:07:25 [Server] INFO at org.bukkit.Location.getBlock(Location.java:87) ~[TacoSpigot-Fantasy.jar:git-PaperSpigot-"010c651"]
11.06 22:07:25 [Server] INFO at com.wasteofplastic.askyblock.GridManager.islandAtLocation(GridManager.java:931) ~[?:?]
11.06 22:07:25 [Server] INFO at com.wasteofplastic.askyblock.commands.IslandCmd.getNextIsland(IslandCmd.java:865) ~[?:?]
11.06 22:07:25 [Server] INFO at com.wasteofplastic.askyblock.commands.IslandCmd.newIsland(IslandCmd.java:686) ~[?:?]
11.06 22:07:25 [Server] INFO at com.wasteofplastic.askyblock.commands.IslandCmd.onCommand(IslandCmd.java:2161) ~[?:?]
11.06 22:07:25 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[TacoSpigot-Fantasy.jar:git-PaperSpigot-"010c651"]
11.06 22:07:25 [Server] INFO ... 11 more

I don't know how to reproduce it, it's just very strange.

**Comment by voodootje0** [comment]
@tastybento I did https://github.com/Fenixin/Minecraft-Region-Fixer but it couldn't find any issues, do you know something else I can try? I don't mind deleting several chunks that could delete islands.

**Comment by tastybento** [comment]
Hmm. You have to find the location where it is happening which may be difficult.  Or if this doesn’t happen that often then maybe ignore it. I’m not sure what else to try.

**Comment by voodootje0** [comment]
It happens all the time, the server is currently broken, no one can make or reset their island.

**Comment by tastybento** [comment]
Try setting startx and startz to some big number, like 500000. That’ll put all new islands away from any old ones.

**Comment by voodootje0** [comment]
Thanks, that fixed the issue!
