### ISSUE TITLE
Loadtime error

### ISSUE THREAD

**Issue by Elithelion** [tastybento/ASkyBlock-Bugs-N-Features#858]
Server Version - spigot-1.12.2

Plugin Version v3.0.9

Upgrade from v3.0.8.2

Error:

[19:02:34 WARN]: java.lang.NullPointerException
[19:02:34 WARN]:        at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:68)
[19:02:34 WARN]:        at com.wasteofplastic.askyblock.PluginConfig.loadPluginConfig(PluginConfig.java:208)
[19:02:34 WARN]:        at com.wasteofplastic.askyblock.ASkyBlock.onEnable(ASkyBlock.java:312)
[19:02:34 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)

What other plugins are you using now?

Plugins (25): CoreProtect, WorldEdit, OpenInv, Essentials, FlatlandsBuilder, ProtocolLib, MagicChest, PermissionsEx, CS-CoreLib, mcMMO, Vault, EssentialsSpawn, ItemRestrict, Orebfuscator4, Rankup, Jobs, PerWorldInventory, mcMMOAction, ASkyBlock, Residence, ChatEx, Multiverse-Core, Multiverse-NetherPortals, MultiWorldMoney, HolographicDisplays

**Steps to make this happen**

1. Just starting the server

**What do you think should happen?**
no errors at all

On a side note, the previous version barfs this error also, I justs didn't catch it before.

**Comment by tastybento** [comment]
It's an error in your chest items in config.yml. Further down in the console log it may say "Problem loading chest item from config.yml so skipping it". Anyway, you need to look at the format of your chest items line. You can post config here (zip it up).
