### ISSUE TITLE
Issues with ASkyBlock v3.0.9.1

### ISSUE THREAD

**Issue by N0tMyFaultOG** [tastybento/ASkyBlock-Bugs-N-Features#870]
**Server version? Remember to say if it is Spigot/Bukkit/Paper etc.**
git-Spigot-2086bb0-2f3ed3b 1.12.2

**Plugin version:**
ASkyBlock v3.0.9.1

**Is this a new install or upgrade from earlier plugin version? If upgrade, what version did you use before?**
It's an upgrade from ASkyBlockv 3.0.9

**(Optional) What other plugins are you using now? (do /plugins and paste text from the console log here)**
CleanroomGenerator, ClearChat, CustomOreGen, PlaceholderAPI, PlugMan, AntiAFKPlus, AJRankFix, ConsoleSpamFix, CustomJoinMessagesPlus, ChatReaction, TitleAPI, Tablist, LuckPerms, VoteRoulette, FastCraft, CustomList, MsgColor, PacketListenerApi, TabRanks, MessageAnnouncer, BuycraftX, AntiRoseGrinder, Votifier, MegaRestart, MVdWPlaceholderAPI, Vouchers, FastAsyncWorldEdit, Emotes, ChatLog, AJSkyblockFly, DeluxeMenus, FeatherBoard, Lottery, mcMMO, Vault, DonorBroadcast, FastAsyncVoxelSniper, EpicRename, TreeTwerk, AuctionHouse, ASkyBlock, ChestCommands, VoxelSniper, ViaVersion, ViaBackwards, WorldEdit, Essentials, HeadDatabase, PermissionTimer, VoidSpawn, ProtocolLib, Multiverse-Core, LibsDisguises, DeluxeChat, KitAdder, Citizens, EssentialsChat, HolographicDisplays, WorldGuard, SkyblockWorldEdit, HideAndCustomPlugins, PlayerReset, SimpleAlias, EssentialsSpawn, CasinoSlots, CustomEnderChest, AJNickname, CrateReloaded, SilkSpawners, NoFlyZone, ShopGUIPlus

**Description of issue. What happened?**
[11:48:58] [Server thread/ERROR]: Could not pass event EntityDamageByBlockEvent to ASkyBlock v3.0.9.1
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[Skyblock.jar:git-Spigot-2086bb0-2f3ed3b]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[Skyblock.jar:git-Spigot-2086bb0-2f3ed3b]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [Skyblock.jar:git-Spigot-2086bb0-2f3ed3b]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [Skyblock.jar:git-Spigot-2086bb0-2f3ed3b]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:93) [Skyblock.jar:git-Spigot-2086bb0-2f3ed3b]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:507) [Skyblock.jar:git-Spigot-2086bb0-2f3ed3b]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.handleNonLivingEntityDamageEvent(CraftEventFactory.java:631) [Skyblock.jar:git-Spigot-2086bb0-2f3ed3b]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.handleNonLivingEntityDamageEvent(CraftEventFactory.java:617) [Skyblock.jar:git-Spigot-2086bb0-2f3ed3b]
	at net.minecraft.server.v1_12_R1.EntityItem.damageEntity(EntityItem.java:256) [Skyblock.jar:git-Spigot-2086bb0-2f3ed3b]
	at net.minecraft.server.v1_12_R1.BlockCactus.a(BlockCactus.java:94) [Skyblock.jar:git-Spigot-2086bb0-2f3ed3b]
	at net.minecraft.server.v1_12_R1.Entity.checkBlockCollisions(Entity.java:961) [Skyblock.jar:git-Spigot-2086bb0-2f3ed3b]
	at net.minecraft.server.v1_12_R1.Entity.move(Entity.java:542) [Skyblock.jar:git-Spigot-2086bb0-2f3ed3b]
	at net.minecraft.server.v1_12_R1.EntityItem.B_(EntityItem.java:86) [Skyblock.jar:git-Spigot-2086bb0-2f3ed3b]
	at net.minecraft.server.v1_12_R1.World.entityJoinedWorld(World.java:1631) [Skyblock.jar:git-Spigot-2086bb0-2f3ed3b]
	at net.minecraft.server.v1_12_R1.World.h(World.java:1601) [Skyblock.jar:git-Spigot-2086bb0-2f3ed3b]
	at net.minecraft.server.v1_12_R1.World.tickEntities(World.java:1435) [Skyblock.jar:git-Spigot-2086bb0-2f3ed3b]
	at net.minecraft.server.v1_12_R1.WorldServer.tickEntities(WorldServer.java:668) [Skyblock.jar:git-Spigot-2086bb0-2f3ed3b]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:817) [Skyblock.jar:git-Spigot-2086bb0-2f3ed3b]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [Skyblock.jar:git-Spigot-2086bb0-2f3ed3b]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [Skyblock.jar:git-Spigot-2086bb0-2f3ed3b]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [Skyblock.jar:git-Spigot-2086bb0-2f3ed3b]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.lang.ClassCastException: org.bukkit.craftbukkit.v1_12_R1.entity.CraftItem cannot be cast to org.bukkit.entity.Player
	at com.wasteofplastic.askyblock.listeners.PlayerEvents.onVisitorGetDamage(PlayerEvents.java:929) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor137.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[Skyblock.jar:git-Spigot-2086bb0-2f3ed3b]
	... 21 more

**Steps to make this happen**

1.  Install the latest build
2. Start the server
3. See the issues

**Comment by N0tMyFaultOG** [comment]
#869 
Even if I'm using ASkyBlock, not the acid one, it seems like over there is the same issue

**Comment by TheWranger** [comment]
Getting this as well. Not sure specifically what action triggers off the error though.

**Comment by kajahofman** [comment]
I have this problem too. Maybe wait for BSkyBlock.

**Comment by TheWranger** [comment]
Pretty sure BSkyblock is still months away from being done

**Comment by gpugeek** [comment]
Getting this as well.
