### ISSUE TITLE
ASkyBlock ERROR. (last update)

### ISSUE THREAD

**Issue by mcgamingf** [tastybento/ASkyBlock-Bugs-N-Features#878]
[10:55:37] [Server thread/ERROR]: Couldn't save chunk; already in use by another instance of Minecraft?
net.minecraft.server.v1_12_R1.ExceptionWorldConflict: Failed to check session lock for world located at ./ASkyBlock, aborting. Stop the server and delete the session.lock in this world to prevent further issues.
at net.minecraft.server.v1_12_R1.WorldNBTStorage.checkSession(WorldNBTStorage.java:85) ~[spigot.jar:git-Spigot-3d850ec-809c399]
at net.minecraft.server.v1_12_R1.World.checkSession(World.java:2814) ~[spigot.jar:git-Spigot-3d850ec-809c399]
at net.minecraft.server.v1_12_R1.ChunkRegionLoader.saveChunk(ChunkRegionLoader.java:127) ~[spigot.jar:git-Spigot-3d850ec-809c399]
at net.minecraft.server.v1_12_R1.ChunkProviderServer.saveChunk(ChunkProviderServer.java:209) [spigot.jar:git-Spigot-3d850ec-809c399]
at net.minecraft.server.v1_12_R1.ChunkProviderServer.unloadChunk(ChunkProviderServer.java:316) [spigot.jar:git-Spigot-3d850ec-809c399]
at net.minecraft.server.v1_12_R1.ChunkProviderServer.unloadChunks(ChunkProviderServer.java:268) [spigot.jar:git-Spigot-3d850ec-809c399]
at net.minecraft.server.v1_12_R1.WorldServer.doTick(WorldServer.java:294) [spigot.jar:git-Spigot-3d850ec-809c399]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:801) [spigot.jar:git-Spigot-3d850ec-809c399]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot.jar:git-Spigot-3d850ec-809c399]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot.jar:git-Spigot-3d850ec-809c399]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot.jar:git-Spigot-3d850ec-809c399]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]

**Comment by mcgamingf** [comment]
Thanks for the help, the problem only appeared after updating ASkyBlock and ViaVersion. And the problem is only in the world of SkyBlock.

**Comment by Poslovitch** [comment]
Hi.

"Last" means nothing. 3.0.8? 3.0.9.1? 3.0.9.3?

The stacktrace you pasted here cannot give us any useful information. Please read this https://www.spigotmc.org/wiki/fixing-plugin-problems-easily-reading-stacktraces/ and provide the useful information so we can help you as fast as possible
