### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by xwxwzzy** [tastybento/ASkyBlock-Bugs-N-Features#890]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version? Remember to say if it is Spigot/Bukkit/Paper etc.**

**Plugin version:**

**Is this a new install or upgrade from earlier plugin version? If upgrade, what version did you use before?**

**(Optional) What other plugins are you using now? (do /plugins and paste text from the console log here)**

**Description of issue. What happened?**

**Steps to make this happen**

1. 1.7.10 KCauldron 1.7.10-R0.1-SNAPSHOT (MC: 1.7.10) 
2. AcidIsland v3.0.9.4
3.I can not use the commands ：
/is top
/is biomes
"An internal error occurred while attempting to perform this command"

**What do you think should happen?**

**Comment by tastybento** [comment]
What errors do you see in the console? Paste them here.

**Comment by xwxwzzy** [comment]
[21:50:26 INFO]: test issued server command: /is top
[21:50:26 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'is' in plugin AcidIsland v3.0.9.4
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[PluginCommand.class:1.7.10-R0.1-SNAPSHOT]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) ~[SimpleCommandMap.class:1.7.10-R0.1-SNAPSHOT]
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:717) ~[CraftServer.class:1.7.10-R0.1-SNAPSHOT]
        at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1317) [nh.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1099) [nh.class:?]
        at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:38) [ir.class:?]
        at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:53) [ir.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245) [ej.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:991) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
Caused by: java.lang.NoClassDefFoundError: com/wasteofplastic/acidisland/TopTen
        at com.wasteofplastic.acidisland.commands.IslandCmd.onCommand(IslandCmd.java:1727) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[PluginCommand.class:1.7.10-R0.1-SNAPSHOT]
        ... 13 more

**Comment by xwxwzzy** [comment]
some new bugs
![bug](https://user-images.githubusercontent.com/42102582/43903600-6484ffb2-9c1f-11e8-82f5-3c8287a9f16f.png)

![bug1 -](https://user-images.githubusercontent.com/42102582/43903659-81e6d0ee-9c1f-11e8-9621-963af98013dd.png)
if some players use commands
：/is controlpanel
：/challenge
they can take out the items inside

sometimes players had gotten the islands
but the plugin told them
them don't have islands

**Comment by tastybento** [comment]
Please read the FAQ about taking items out of the GUI. It's another plugin problem.

**Comment by xwxwzzy** [comment]
can I ues the commands -
/is top
/is biomes
in the next version?

**Comment by tastybento** [comment]
Do you mean in BSkyBlock? /is top is done, yes. /is biomes is still TBD.

**Comment by xwxwzzy** [comment]
I mean AcidIsland

**Comment by tastybento** [comment]
I don't fully understand your question, but both those commands are supported.

**Comment by xwxwzzy** [comment]
I use AcidIsland v3.0.9.4
I can not use /is top
