### ISSUE TITLE
No enum constant STONEBRICK

### ISSUE THREAD

**Issue by goldmorphin** [tastybento/ASkyBlock-Bugs-N-Features#907]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version? Remember to say if it is Spigot/Bukkit/Paper etc.**
Spigot 1.8.8

**Plugin version:**
Latest
**Is this a new install or upgrade from earlier plugin version? If upgrade, what version did you use before?**
New install
**(Optional) What other plugins are you using now? (do /plugins and paste text from the console log here)**
None

**Description of issue. What happened?**
[05:38:41 ERROR]: Could not parse item [STONEBRICK] in schematic - skipping!
[05:38:41 WARN]: java.lang.IllegalArgumentException: No enum constant org.bukkit.Material.STONEBRICK
[05:38:41 WARN]:        at java.lang.Enum.valueOf(Enum.java:238)
[05:38:41 WARN]:        at org.bukkit.Material.valueOf(Material.java:65)
[05:38:41 WARN]:        at com.wasteofplastic.askyblock.schematics.IslandBlock.setChest(IslandBlock.java:499)
[05:38:41 WARN]:        at com.wasteofplastic.askyblock.schematics.Schematic.prePasteSchematic(Schematic.java:1199)
[05:38:41 WARN]:        at com.wasteofplastic.askyblock.schematics.Schematic.<init>(Schematic.java:645)

Screenshot: https://i.gyazo.com/9f0c05af4c241cc2769e876a84cfc99f.png

**Steps to make this happen**

1. Put stonebricks in chest
2. Create schematic with these chest
3. Add schematic in ASkyBlock

**What do you think should happen?**
Everything should work.

**Comment by tastybento** [comment]
There is no STONEBRICK Material in the server you are using. So, it looks like the schematic was made on one version but tried to be used on another version. FYI, the actual material value is STONE_BRICKS. https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Tag.html#STONE_BRICKS

So, make schematics on the same version of server as you use to play. If you are doing that, then it's not supported.
