### ISSUE TITLE
NPE on pasting ItemFrame

### ISSUE THREAD

**Issue by goldmorphin** [tastybento/ASkyBlock-Bugs-N-Features#909]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version? Remember to say if it is Spigot/Bukkit/Paper etc.**
Spigot 1.8.8

**Plugin version:**
Latest (3.0.9.4)

**Is this a new install or upgrade from earlier plugin version? If upgrade, what version did you use before?**
New install

**(Optional) What other plugins are you using now? (do /plugins and paste text from the console log here)**
None

**Description of issue. What happened?**
NPE when pasting schematics with ItemFrame.
`[05:52:25 ERROR]: Could not pass event InventoryClickEvent to ASkyBlock v3.0.9.4
org.bukkit.event.EventException
>       at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[skyblock.jar:git-Spigot-cef2f81-unknown]
>       at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[skyblock.jar:git-Spigot-cef2f81-unknown]
>       at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [skyblock.jar:git-Spigot-cef2f81-unknown]
>       at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [skyblock.jar:git-Spigot-cef2f81-unknown]
>       at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1684) [skyblock.jar:git-Spigot-cef2f81-unknown]
>       at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:31) [skyblock.jar:git-Spigot-cef2f81-unknown]
>       at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:9) [skyblock.jar:git-Spigot-cef2f81-unknown]
>       at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [skyblock.jar:git-Spigot-cef2f81-unknown]
>       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_181]
>       at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_181]
>       at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [skyblock.jar:git-Spigot-cef2f81-unknown]
>       at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [skyblock.jar:git-Spigot-cef2f81-unknown]
>       at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:401) [skyblock.jar:git-Spigot-cef2f81-unknown]
>       at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [skyblock.jar:git-Spigot-cef2f81-unknown]
>       at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [skyblock.jar:git-Spigot-cef2f81-unknown]
>       at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: org.bukkit.command.CommandException: Unhandled exception executing command 'island' in plugin ASkyBlock v3.0.9.4
>       at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[skyblock.jar:git-Spigot-cef2f81-unknown]
>       at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:142) ~[skyblock.jar:git-Spigot-cef2f81-unknown]
>       at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:636) ~[skyblock.jar:git-Spigot-cef2f81-unknown]
>       at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.performCommand(CraftPlayer.java:242) ~[skyblock.jar:git-Spigot-cef2f81-unknown]
>       at com.wasteofplastic.askyblock.util.Util.runCommand(Util.java:573) ~[?:?]
>       at com.wasteofplastic.askyblock.panels.SchematicsPanel.onInventoryClick(SchematicsPanel.java:152) ~[?:?]
>       at sun.reflect.GeneratedMethodAccessor225.invoke(Unknown Source) ~[?:?]
>       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
>       at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
>       at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[skyblock.jar:git-Spigot-cef2f81-unknown]
>       ... 15 more
Caused by: java.lang.NullPointerException
>       at com.wasteofplastic.askyblock.schematics.Schematic.pasteSchematic(Schematic.java:865) ~[?:?]
>       at com.wasteofplastic.askyblock.commands.IslandCmd.newIsland(IslandCmd.java:738) ~[?:?]
>       at com.wasteofplastic.askyblock.commands.IslandCmd.onCommand(IslandCmd.java:2118) ~[?:?]
>       at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[skyblock.jar:git-Spigot-cef2f81-unknown]
>       at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:142) ~[skyblock.jar:git-Spigot-cef2f81-unknown]
>       at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:636) ~[skyblock.jar:git-Spigot-cef2f81-unknown]
>       at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.performCommand(CraftPlayer.java:242) ~[skyblock.jar:git-Spigot-cef2f81-unknown]
>       at com.wasteofplastic.askyblock.util.Util.runCommand(Util.java:573) ~[?:?]
>       at com.wasteofplastic.askyblock.panels.SchematicsPanel.onInventoryClick(SchematicsPanel.java:152) ~[?:?]
>       at sun.reflect.GeneratedMethodAccessor225.invoke(Unknown Source) ~[?:?]
>       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
>       at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
>       at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[skyblock.jar:git-Spigot-cef2f81-unknown]
>       ... 15 more
`
**Steps to make this happen**

1. Create schematic with ItemFrames
2. Add it in ASkyBlock

**What do you think should happen?**
Item Frames must be added in world.

**Comment by tastybento** [comment]
Noted. Sorry, this will not be fixed because we're not supporting ASB now.
