### ISSUE TITLE
Island Protection Error

### ISSUE THREAD

**Issue by ardagokcek** [tastybento/ASkyBlock-Bugs-N-Features#95]
I got this error and users can modify other users islands. And in some islands plugin says to owner "This island is protected."

 [00:05:06] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'is' in plugin ASkyBlock v3.0.6.1
 at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched.jar:git-PaperSpigot-"4c7641d"]
 at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:146) ~[patched.jar:git-PaperSpigot-"4c7641d"]
 at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:666) ~[patched.jar:git-PaperSpigot-"4c7641d"]
 at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1189) [patched.jar:git-PaperSpigot-"4c7641d"]
 at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1001) [patched.jar:git-PaperSpigot-"4c7641d"]
 at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [patched.jar:git-PaperSpigot-"4c7641d"]
 at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [patched.jar:git-PaperSpigot-"4c7641d"]
 at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [patched.jar:git-PaperSpigot-"4c7641d"]
 at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_121]
 at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_121]
 at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [patched.jar:git-PaperSpigot-"4c7641d"]
 at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774) [patched.jar:git-PaperSpigot-"4c7641d"]
 at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [patched.jar:git-PaperSpigot-"4c7641d"]
 at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [patched.jar:git-PaperSpigot-"4c7641d"]
 at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched.jar:git-PaperSpigot-"4c7641d"]
 at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]

**Comment by tastybento** [comment]
I think there should be more lines to this error because there is no "Caused by" in there.

It sounds like your islands.yml is corrupted. Stop server, move island.yml to islands.old. Restart server. You will need to set the island spawn again if you had one.

**Comment by ardagokcek** [comment]
I found some islands that owners uuid is "null" then I searched that islands and found the owners uuid and replaced it. I found out that our admin changed distance and protection range so island data has corrupted. I fixed island data but when you create a island market visitors can place block and kill mobs.

iPhone'umdan gönderildi

tastybento <notifications@github.com<mailto:notifications@github.com>> şunları yazdı (6 Nis 2017 07:38):


I think there should be more lines to this error because there is no "Caused by" in there.

It sounds like your islands.yml is corrupted. Stop server, move island.yml to islands.old. Restart server. You will need to set the island spawn again if you had one.

**Comment by ardagokcek** [comment]
I found out that plugin creates this bug from islands.yml
When I delete islands.yml, plugin takes coordinates and fixes islands.yml from players. But when it is taking coordinates it doesn't takes protection range.
"
Like my player data is 
 `islandLocation: ASkyBlock:-1800:115:-1200:0:0`

So can you fix this? My distance is 200 and protection range is 100

**Comment by ardagokcek** [comment]
I can send you our islands.yml and players folder to check it. It seems OK but it has bugs.

**Comment by tastybento** [comment]
Best to use pastebin.com and paste the link if you want to do that.

**Comment by ardagokcek** [comment]
Here you are "islands.yml":
https://pastebin.com/6rSZFiqK

**Comment by ardagokcek** [comment]
You can come to our server and try it. (mc.oyunbaz.network) It is Turkish server and you can add me from Skype for faster response (my username is ardagokcek027).

**Comment by tastybento** [comment]
Thanks for the report, but I can't replicate this issue right now. If the islands.yml is removed and regenerated, the distance and protection numbers are in the new data created. Also, in your islands.yml file all the data is there.
