### ISSUE TITLE
After seting entity limits

### ISSUE THREAD

**Issue by wasder** [tastybento/ASkyBlock-Bugs-N-Features#98]
```
[23:24:21] [Server thread/INFO]: [ASkyBlock] Enabling ASkyBlock v3.0.6.1
[23:24:21] [Thread-31/INFO]: [AsyncWorldEdit] You have an old version of the plugin. Your version: 3.4.8, available version: 3.4.9
[23:24:21] [Server thread/INFO]: [ASkyBlock] BLAZE will be limited to 10
[23:24:21] [Server thread/INFO]: [ASkyBlock] CAVE_SPIDER will be limited to 10
[23:24:21] [Server thread/INFO]: [ASkyBlock] CHICKEN will be limited to 25
[23:24:21] [Server thread/INFO]: [ASkyBlock] COW will be limited to 25
[23:24:21] [Server thread/INFO]: [ASkyBlock] HORSE will be limited to 20
[23:24:21] [Server thread/INFO]: [ASkyBlock] MAGMA_CUBE will be limited to 10
[23:24:21] [Server thread/INFO]: [ASkyBlock] MUSHROOM_COW will be limited to 25
[23:24:21] [Server thread/INFO]: [ASkyBlock] OCELOT will be limited to 25
[23:24:21] [Server thread/INFO]: [ASkyBlock] PIG will be limited to 25
[23:24:21] [Server thread/INFO]: [ASkyBlock] PIG_ZOMBIE will be limited to 10
[23:24:21] [Server thread/INFO]: [ASkyBlock] RABBIT will be limited to 25
[23:24:21] [Server thread/INFO]: [ASkyBlock] SHEEP will be limited to 25
[23:24:21] [Server thread/INFO]: [ASkyBlock] SKELETON will be limited to 10
[23:24:21] [Server thread/INFO]: [ASkyBlock] SLIME will be limited to 20
[23:24:21] [Server thread/INFO]: [ASkyBlock] SPIDER will be limited to 10
[23:24:21] [Server thread/INFO]: [ASkyBlock] WITHER will be limited to 10
[23:24:21] [Server thread/INFO]: [ASkyBlock] WITHER_SKELETON will be limited to 10
[23:24:21] [Server thread/ERROR]: Error occurred while enabling ASkyBlock v3.0.6.1 (Is it up to date?)
java.lang.IllegalArgumentException: No enum constant org.bukkit.entity.EntityType.WITHER_SKELETON
	at java.lang.Enum.valueOf(Enum.java:238) ~[?:1.8.0_74]
	at org.bukkit.entity.EntityType.valueOf(EntityType.java:1) ~[spigot.jar:git-Spigot-c6871e2-0cd0397]
	at com.wasteofplastic.askyblock.PluginConfig.loadPluginConfig(PluginConfig.java:523) ~[?:?]
	at com.wasteofplastic.askyblock.ASkyBlock.onEnable(ASkyBlock.java:282) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) ~[spigot.jar:git-Spigot-c6871e2-0cd0397]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot.jar:git-Spigot-c6871e2-0cd0397]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-c6871e2-0cd0397]
	at org.bukkit.craftbukkit.v1_9_R2.CraftServer.loadPlugin(CraftServer.java:362) [spigot.jar:git-Spigot-c6871e2-0cd0397]
	at org.bukkit.craftbukkit.v1_9_R2.CraftServer.enablePlugins(CraftServer.java:322) [spigot.jar:git-Spigot-c6871e2-0cd0397]
	at net.minecraft.server.v1_9_R2.DedicatedServer.init(DedicatedServer.java:201) [spigot.jar:git-Spigot-c6871e2-0cd0397]
	at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:532) [spigot.jar:git-Spigot-c6871e2-0cd0397]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]
```

**Comment by tastybento** [comment]
There is no WITHER_SKELETON in 1.9. You need to remove that from your config.

**Comment by wasder** [comment]
How it is called in 1.9?

**Comment by tastybento** [comment]
Just SKELETON. There's no specific wither skelly entity.

**Comment by wasder** [comment]
Ah okay.
